MULE-19279: Incorrect converter being chosen for certain serialization use cases
mulesoft/mule pull request #10204
Opened 2021-03-22 19:00 UTC by sofiamorseletto

2021-03-23 18:33 UTC, eze210 approved these changes

2021-03-23 18:34 UTC, eze210 requested changes
Please add a test

2021-03-23 18:35 UTC, elrodro83 submitted a review, later dismissed

2021-03-31 12:33 UTC, sofiamorseletto commented
--validate

2021-03-31 14:19 UTC, eze210 approved these changes

2021-03-31 17:48 UTC, merged