MULE-19327: Added support for conditional closing of the connection f…
mulesoft/mule pull request #10259
Opened 2021-04-12 17:28 UTC by nicomz

…actory on stop

2021-04-12 18:33 UTC, juldiazmule approved these changes

2021-04-12 20:36 UTC, fsgonz requested changes
Add tests.

2021-04-12 20:36 UTC, fsgonz commented on transports/jms/src/main/java/org/mule/transport/jms/JmsConnector.java
> +                if(Boolean.valueOf( System.getProperty(MULE_JMS_CLOSE_CONNECTION_FACTORY_ON_STOP, "false")))
Remove space. Use static import if possible

2021-04-12 20:36 UTC, fsgonz commented on transports/jms/src/main/java/org/mule/transport/jms/JmsConnector.java
> +                if(Boolean.valueOf( System.getProperty(MULE_JMS_CLOSE_CONNECTION_FACTORY_ON_STOP, "false")))
You can you Boolean.getBoolean

2021-04-14 13:04 UTC, fsgonz approved these changes

2021-04-14 13:05 UTC, merged