MULE-19428: Add localisation properties extension tests
mulesoft/mule pull request #10363
Opened 2021-05-19 19:03 UTC by sofiamorseletto

2021-05-19 19:53 UTC, sofiamorseletto commented
--validate

2021-05-20 12:09 UTC, sofiamorseletto commented
--validate

2021-05-20 12:26 UTC, elrodro83 requested changes

2021-05-20 12:26 UTC, elrodro83 commented on tests/test-extensions/test-localisation-properties-extension/src/main/java/org/mule/test/crafted/localisation/properties/extension/LocalisationConfigurationPropertiesProvider.java
> +          NumberFormat nf = NumberFormat.getInstance(new Locale("pt", "PT"));
get the `pt`, `PT` values from the `configurationAttributeKey` so that test cases for other locales can be added easily if needed.

2021-05-21 12:39 UTC, elrodro83 requested changes

2021-05-21 12:39 UTC, elrodro83 commented on tests/test-extensions/test-localisation-properties-extension/src/main/java/org/mule/test/crafted/localisation/properties/extension/LocalisationConfigurationPropertiesProviderFactory.java
> +    Preconditions.checkArgument(file != null, "Required attribute 'file' of 'locale-configuration-properties' not found");
use `Objects.requireNotNull` instead

2021-05-21 14:40 UTC, sofiamorseletto commented
--validate

2021-05-21 15:17 UTC, sofiamorseletto commented
--validate

2021-05-21 17:33 UTC, elrodro83 approved these changes

2021-05-21 18:07 UTC, merged