MULE-19402: FeatureFlaggingService improvement
mulesoft/mule pull request #10390
Opened 2021-06-02 06:40 UTC by IvanAndresFritzler

2021-06-02 13:17 UTC, elrodro83 requested changes

2021-06-02 13:17 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/api/config/FeatureContext.java
> + * @since 4.4.0
add 4.3.1

2021-06-02 13:17 UTC, elrodro83 commented on modules/deployment-model-impl/src/main/java/org/mule/runtime/module/deployment/impl/internal/config/FeatureFlaggingUtils.java
> + * @since 4.4.0
4.3.1

2021-06-02 14:05 UTC, elrodro83 approved these changes

2021-06-03 13:25 UTC, IvanAndresFritzler commented
--validate

2021-06-03 16:31 UTC, merged