EE-7726: Add logging to correlate flow components, events with thread…
mulesoft/mule pull request #10399
Opened 2021-06-04 12:50 UTC by fsgonz

… and thread jumps.

2021-06-04 12:51 UTC, fsgonz commented
Do not review yet.

2021-06-07 18:34 UTC, fsgonz commented
--validate

2021-06-10 21:09 UTC, elrodro83 requested changes

2021-06-10 21:09 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/construct/AbstractFlowConstruct.java
> +  protected void doInitialiseProcessingStrategy() throws MuleException {
add javadoc

2021-06-10 21:09 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/management/execution/DefaultExecutionOrchestrator.java
> + * @since 4.4.0, 4.3.1
will this be cherrypicked to 4.3?

2021-06-10 21:09 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/management/execution/ProcessingStrategyExecutionProfiler.java
> + *
add `<p>` separators

2021-06-10 21:09 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/management/execution/LoggerProcessingStrategyExecutionProfiler.java
> +    log(LOG_AFTER_DISPATCHING_TO_FLOW,
neware, you are evaluating `Long.toString ` even if won;t be logged because of log level.

2021-06-10 21:09 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/management/execution/ExecutionOrchestrator.java
> +  Scheduler getContextScheduler();
javadoc

2021-06-10 21:09 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/processor/strategy/StreamEmitterProcessingStrategyFactory.java
> +import static java.lang.Long.MIN_VALUE;
static imports go first

2021-06-10 21:09 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/processor/strategy/StreamEmitterProcessingStrategyFactory.java
> +import java.util.function.*;
no *

2021-06-10 21:09 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/processor/strategy/enricher/AbstractProcessingStrategyEnricher.java
> +                                                        .createStaticMessage("Could not enrich for processing type "
static import

2021-06-10 21:09 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/processor/strategy/enricher/AbstractProcessingStrategyEnricher.java
> +  protected abstract ReactiveProcessor doCreateProcessingStrategyChain(ReactiveProcessor processor);
javadoc

2021-06-10 21:09 UTC, elrodro83 commented on tests/allure/src/main/java/org/mule/test/allure/AllureConstants.java
> +  interface ManagementFeature {
woudln't "TroubleshootingFeature be more accurate"?

2021-06-17 04:18 UTC, closed without merging