EE-7827: App is unable to resolve mule-scripting
mulesoft/mule pull request #10407
Opened 2021-06-07 14:49 UTC by marianorean

2021-06-09 15:31 UTC, IvanAndresFritzler requested changes

2021-06-09 15:31 UTC, IvanAndresFritzler commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/SpringXmlConfigurationBuilder.java
> +    muleContext.getInjector().inject(this);
Use LifecycleUtils.initialiseIfNeeded

2021-06-09 15:31 UTC, IvanAndresFritzler commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/SpringXmlConfigurationBuilder.java
> +    muleContext.getInjector().inject(this);
Cant't we do this injection at an earlier point (I'm thinking in the doConfigure method) and avoid passing the muleContext around?

2021-06-09 15:51 UTC, IvanAndresFritzler commented
I think that we need a test to ensure that this feature flag is kept in place.

2021-06-10 17:05 UTC, marianorean commented
--validate

2021-06-15 16:06 UTC, IvanAndresFritzler requested changes

2021-06-15 16:06 UTC, IvanAndresFritzler commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/SpringXmlConfigurationBuilder.java
> +  AstXmlParser getParser() {
Can this be protected?

2021-06-15 16:06 UTC, IvanAndresFritzler commented on modules/spring-config/src/test/java/org/mule/runtime/config/internal/SpringXmlConfigurationBuilderTestCase.java
> +    assertThat(((DefaultAstXmlParser) configurationBuilder.getParser()).getFailStrategy(),
can we avoid the insanceOf and just try to parse something?

2021-06-17 20:15 UTC, IvanAndresFritzler requested changes

2021-06-17 20:15 UTC, IvanAndresFritzler commented on modules/spring-config/src/test/java/org/mule/runtime/config/internal/SpringXmlConfigurationBuilderTestCase.java
> +import static org.hamcrest.Matchers.containsString;
static imports go first

2021-06-17 20:15 UTC, IvanAndresFritzler commented on modules/spring-config/src/test/java/org/mule/runtime/config/internal/SpringXmlConfigurationBuilderTestCase.java
> +import io.qameta.allure.Issue;
io.* and org.junit.* after org.mule.* and java/javax.*

2021-06-17 20:15 UTC, IvanAndresFritzler commented on modules/spring-config/src/test/java/org/mule/runtime/config/internal/SpringXmlConfigurationBuilderTestCase.java
> +import javax.inject.Inject;
javax.* after java.*

2021-06-17 20:41 UTC, IvanAndresFritzler requested changes

2021-06-17 20:41 UTC, IvanAndresFritzler commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/SpringXmlConfigurationBuilder.java
> +import javax.inject.Inject;
right after org.mule.*

2021-06-17 22:58 UTC, IvanAndresFritzler approved these changes

2021-06-17 23:26 UTC, merged