MULE-19361: MULE-19361: add ParameterGroupModel as key for Parameters map
mulesoft/mule pull request #10423
Opened 2021-06-16 17:49 UTC by jcgrethe

2021-06-17 13:40 UTC, jcgrethe commented
--validate

2021-06-22 17:09 UTC, elrodro83 requested changes

2021-06-22 17:09 UTC, elrodro83 commented on modules/extensions-spring-support/src/test/java/org/mule/test/module/extension/config/MultipleParametersGroupTestCase.java
> +  public void getInlineGroupDefinition() throws Exception {
allure issue annotation

2021-06-22 17:09 UTC, elrodro83 commented on modules/extensions-spring-support/src/test/java/org/mule/test/module/extension/config/MultipleParametersGroupTestCase.java
> +  protected String[] getConfigFiles() {
why not use `getConfigFile`?

2021-06-22 17:09 UTC, elrodro83 commented on modules/extensions-spring-support/src/test/java/org/mule/test/module/extension/config/MultipleParametersGroupTestCase.java
> +  }
remove this, doesn't seem to be needed

2021-06-22 17:09 UTC, elrodro83 commented on modules/extensions-spring-support/src/test/java/org/mule/test/module/extension/config/MultipleParametersGroupTestCase.java
> +    Message message = flowRunner("getBarberPreferences").withPayload(EMPTY_STRING).run().getMessage();
do you actually need to set the empty payload?

2021-06-22 19:32 UTC, elrodro83 approved these changes

2021-06-22 19:52 UTC, jcgrethe commented
--validate

2021-06-22 20:59 UTC, merged