MULE-19092: fix munit tests
mulesoft/mule pull request #10445
Opened 2021-06-24 15:51 UTC by jcgrethe

2021-06-24 18:55 UTC, elrodro83 requested changes

2021-06-24 18:55 UTC, elrodro83 commented on core-tests/src/test/java/org/mule/runtime/core/internal/processor/interceptor/ReactiveInterceptorAdapterTestCase.java
> +      verify(interceptor, atLeastOnce()).getClass().getClassLoader();
create a different set of test cases to assert this specifically,

2021-06-24 18:55 UTC, elrodro83 commented on core-tests/src/test/java/org/mule/runtime/core/internal/processor/interceptor/ReactiveInterceptorAdapterTestCase.java
> +      verify(interceptor, atLeastOnce()).getClass().getClassLoader();
i think this is just testing that getClass was called, but not getClassloader. Is there a more expressive way to verify the expected behavior?

2021-06-25 18:56 UTC, jcgrethe commented
--validate

2021-06-28 12:25 UTC, jcgrethe commented
--validate

2021-06-28 19:34 UTC, jcgrethe commented
--validate

2021-06-29 14:53 UTC, merged