CMTS-224: Add cache to field value provider resolution
mulesoft/mule pull request #10481
Opened 2021-07-15 09:27 UTC by lucianoRM

2021-07-15 13:42 UTC, gsfernandes requested changes

2021-07-15 13:42 UTC, gsfernandes commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/internal/runtime/operation/OperationMessageProcessor.java
> +import javax.inject.Inject;
no need for this change on this PR

2021-07-16 19:23 UTC, gsfernandes approved these changes

2021-07-19 08:47 UTC, lucianoRM commented
--validate

2021-07-20 06:41 UTC, lucianoRM commented
--validate

2021-07-20 16:59 UTC, gsfernandes approved these changes

2021-07-21 06:47 UTC, merged