Mule 19545
mulesoft/mule pull request #10490
Opened 2021-07-16 20:02 UTC by mbuchwald

2021-07-19 18:58 UTC, elrodro83 requested changes
See if `CommonComponentBeanDefinitionCreator#processMuleProperties` can also be removed

2021-07-19 18:58 UTC, elrodro83 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/dsl/processor/ObjectTypeVisitor.java
> +      type = ClassUtils.getClass(Thread.currentThread().getContextClassLoader(),
static import

2021-07-19 18:58 UTC, elrodro83 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/dsl/spring/BeanDefinitionFactory.java
> -    PropertiesMapBeanDefinitionCreator propertiesMapBeanDefinitionCreator = new PropertiesMapBeanDefinitionCreator();
![image](https://user-images.githubusercontent.com/8010105/126212105-2d78a35d-f2cc-40ee-bbd1-6e674668776a.png)

2021-07-19 18:58 UTC, elrodro83 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/dsl/spring/ObjectBeanDefinitionCreator.java
> +        component.getParameter(REF_PARAMETER) != null ? component.getParameter(REF_PARAMETER).getResolvedRawValue() : null;
avoid the double lookup of the parameter

2021-07-19 18:58 UTC, elrodro83 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/dsl/spring/ObjectBeanDefinitionCreator.java
> +        component.getParameter(CLASS_PARAMETER) != null ? component.getParameter(CLASS_PARAMETER).getResolvedRawValue() : null;
avoid the double lookup of the parameter

2021-07-19 18:58 UTC, elrodro83 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/dsl/spring/PropertyComponentUtils.java
> +    Object value;
is this method still needed at all?

2021-07-20 19:07 UTC, mbuchwald commented
--validate

2021-07-21 13:26 UTC, elrodro83 approved these changes

2021-07-21 14:12 UTC, elrodro83 approved these changes

2021-07-21 14:20 UTC, elrodro83 requested changes

2021-07-21 14:20 UTC, elrodro83 commented on tests/allure/src/main/java/org/mule/test/allure/AllureConstants.java
> +<<<<<<< HEAD
!!!!

2021-07-21 14:20 UTC, mbuchwald commented on tests/allure/src/main/java/org/mule/test/allure/AllureConstants.java
> +<<<<<<< HEAD
Uh la re con...

2021-07-21 14:21 UTC, elrodro83 approved these changes

2021-07-21 14:28 UTC, mbuchwald commented
--validate

2021-07-21 15:53 UTC, merged