MULE-19707: Changes in the SDK execution engine are causing NPE excep…
mulesoft/mule pull request #10665
Opened 2021-08-18 20:40 UTC by IvanAndresFritzler

…tion

2021-08-18 21:11 UTC, IvanAndresFritzler commented
--validate

2021-08-18 22:05 UTC, IvanAndresFritzler commented
--validate

2021-08-18 22:17 UTC, fsgonz commented
--validate

2021-08-18 22:45 UTC, fsgonz commented
--validate

2021-08-18 23:19 UTC, fsgonz commented
--validate

2021-08-19 11:11 UTC, fsgonz commented
--validate

2021-08-19 13:46 UTC, elrodro83 requested changes

2021-08-19 13:46 UTC, elrodro83 commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/internal/runtime/operation/DefaultExecutionMediator.java
> +      LOGGER.warn("An exception has been thrown during the operation error handling", handlingException);
`error` instead of `warn`?

2021-08-19 16:22 UTC, elrodro83 approved these changes

2021-08-19 18:30 UTC, merged