MULE-19735: Make async delegation initialise processing strategy
mulesoft/mule pull request #10701
Opened 2021-08-24 23:21 UTC by fsgonz

2021-08-24 23:39 UTC, IvanAndresFritzler submitted a review, later dismissed

2021-08-24 23:58 UTC, elrodro83 requested changes

2021-08-24 23:58 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/processor/AsyncDelegateMessageProcessor.java
> +    initialiseIfNeeded(processingStrategy, muleContext);
missing a call to dispose

2021-08-24 23:58 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/processor/AsyncDelegateMessageProcessor.java
> +    initialiseIfNeeded(processingStrategy, muleContext);
this should go on `initialize`, not `start`

2021-08-25 01:01 UTC, elrodro83 approved these changes

2021-08-25 01:22 UTC, merged