MULE-19596: Implement a profiling data consumer discovery strategy based on server plugins
mulesoft/mule pull request #10724
Opened 2021-08-31 04:06 UTC by IvanAndresFritzler

2021-09-01 16:20 UTC, fsgonz requested changes

2021-09-01 16:20 UTC, fsgonz commented on core-tests/src/test/java/org/mule/runtime/core/internal/profiling/discovery/CompositeProfilingDataConsumerDiscoveryStrategyTestCase.java
> +public class CompositeProfilingDataConsumerDiscoveryStrategyTestCase {
allure annotations,

2021-09-01 16:20 UTC, fsgonz commented on core/src/main/java/org/mule/runtime/core/internal/config/builders/DefaultsConfigurationBuilder.java
> +import java.util.Optional;
Not used.

2021-09-01 16:20 UTC, fsgonz commented on core/src/main/java/org/mule/runtime/core/internal/profiling/DefaultProfilingService.java
> +  private Optional<Set<ProfilingDataConsumerDiscoveryStrategy>> profilingDataConsumerDiscoveryStrategies = Optional.empty();
static import

2021-09-01 16:57 UTC, elrodro83 requested changes

2021-09-01 16:57 UTC, elrodro83 commented on core-tests/src/test/java/org/mule/runtime/core/internal/profiling/discovery/CompositeProfilingDataConsumerDiscoveryStrategyTestCase.java
> +    when(discoveryStrategyTwo.discover()).thenAnswer(invocation -> Collections.singleton(profilingDataConsumerTwo));
static imports

2021-09-02 13:06 UTC, fsgonz approved these changes

2021-09-02 13:26 UTC, elrodro83 requested changes

2021-09-02 13:26 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/profiling/discovery/CompositeProfilingDataConsumerDiscoveryStrategy.java
> +  Set<ProfilingDataConsumerDiscoveryStrategy> discoveryStrategies;
private?

2021-09-02 14:33 UTC, elrodro83 approved these changes

2021-09-02 16:25 UTC, merged