Extract Mvel support to its own module
mulesoft/mule pull request #10746
Opened 2021-09-03 02:08 UTC by elrodro83

2021-09-07 11:31 UTC, elrodro83 commented
--validate

2021-09-07 11:54 UTC, elrodro83 commented
--validate

2021-09-07 19:59 UTC, fsgonz requested changes

2021-09-07 19:59 UTC, fsgonz commented on core-tests/src/test/java/org/mule/runtime/core/internal/el/dataweave/ExtendedExpressionDwLanguageAdapterTestCase.java
> +  @Description("Verifies that global binding context only work for DW.")
work -> works

2021-09-08 12:30 UTC, fsgonz approved these changes

2021-09-08 13:09 UTC, merged