EE-7886: Implement an agnostic way to inject diagnostic info for connectors
mulesoft/mule pull request #10765
Opened 2021-09-13 16:03 UTC by fsgonz

2021-09-15 21:09 UTC, elrodro83 requested changes

2021-09-15 21:09 UTC, elrodro83 commented on core-tests/src/test/java/org/mule/runtime/core/api/profiling/DefaultProfilingServiceTestCase.java
> +        .setProfilingDataConsumerDiscoveryStrategies(of(Collections.singleton(new TestProfilingDataConsumerDiscoveryStrategy())));
static import

2021-09-16 12:55 UTC, elrodro83 approved these changes

2021-09-16 17:35 UTC, eze210 approved these changes

2021-09-16 18:54 UTC, merged