MULE-19146: Passing the URL to the parse method of AstXmlParser in order to have the metadata available.
mulesoft/mule pull request #10803
Opened 2021-09-20 21:51 UTC by asanguinetti

2021-09-21 13:48 UTC, elrodro83 submitted a review, later dismissed

2021-09-21 19:57 UTC, elrodro83 requested changes

2021-09-21 19:57 UTC, elrodro83 commented on modules/spring-config/src/test/java/org/mule/runtime/config/internal/SpringXmlConfigurationBuilderTestCase.java
> +    Thread.currentThread().setContextClassLoader(applicationClassLoader);
use ClassUtils.withContextClassloader

2021-09-21 19:57 UTC, elrodro83 commented on modules/spring-config/src/test/java/org/mule/runtime/config/internal/SpringXmlConfigurationBuilderTestCase.java
> +    FileUtils.copyURLToFile(originalResource, simpleAppFileOutsideClassPath);
static import

2021-09-21 20:10 UTC, elrodro83 approved these changes

2021-09-22 01:22 UTC, asanguinetti commented
--validate

2021-09-22 03:09 UTC, merged