MULE-19928: initialize object store inside redelivery policy
mulesoft/mule pull request #10971
Opened 2021-11-12 18:36 UTC by jcgrethe

2021-11-12 20:28 UTC, jcgrethe commented
--validate

2021-11-15 13:31 UTC, elrodro83 requested changes

2021-11-15 13:31 UTC, elrodro83 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/model/ComponentModel.java
> +    componentModel.getParent().getInnerComponents().stream()
add a comment explaining the situation why thos code is needed and what it does

2021-11-15 13:31 UTC, elrodro83 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/model/ComponentModel.java
> +        .filter(innerComponentModel -> innerComponentModel.getIdentifier().getName().equals("redelivery-policy")).findAny()
reuse an already exsiting constant

2021-11-15 13:31 UTC, elrodro83 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/model/ComponentModel.java
> +              .filter(parameterModel -> parameterModel.getName().equals("redeliveryPolicy")).findAny()
constant

2021-11-15 13:31 UTC, elrodro83 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/model/ComponentModel.java
> +        .filter(innerComponentModel -> innerComponentModel.getIdentifier().getName().equals("redelivery-policy")).findAny()
be careful, you are ignoring the namespace of the component here

2021-11-15 17:09 UTC, elrodro83 requested changes

2021-11-15 17:09 UTC, elrodro83 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/model/ComponentModel.java
> +    //MULE-19928: munit tests fail to initialize an object store inside a redelivery policy.
explain the fix, not the symptom of the issue

2021-11-15 17:09 UTC, elrodro83 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/model/ComponentModel.java
> +        .filter(innerComponentModel -> innerComponentModel.getIdentifier().getName().equals(REDELIVERY_POLICY_ELEMENT_IDENTIFIER)
still using just the name here, use the full identifier for equality check

2021-11-15 18:35 UTC, elrodro83 approved these changes

2021-11-15 20:16 UTC, merged