MULE-19921: Redelivery Policy: infinite loop with blank message ID in a source configured with transactions
mulesoft/mule pull request #10985
Opened 2021-11-15 23:40 UTC by rbourbonnavarro

2021-11-16 13:37 UTC, elrodro83 requested changes

2021-11-16 13:37 UTC, elrodro83 commented on modules/core-components/src/main/java/org/mule/runtime/core/internal/processor/IdempotentRedeliveryPolicy.java
> +    } catch (ObjectStoreException e) {
what if there was another problem in the object store not related to the key being null?

2021-11-16 15:35 UTC, elrodro83 approved these changes

2021-11-16 18:01 UTC, rbourbonnavarro commented
--validate

2021-11-16 20:53 UTC, rbourbonnavarro commented
--validate

2021-11-17 00:07 UTC, rbourbonnavarro commented
--validate

2021-11-17 01:48 UTC, merged