EE-8102: Implement a way to to enable/disable profiling at runtime
mulesoft/mule pull request #11035
Opened 2021-12-06 14:51 UTC by fsgonz

2021-12-09 18:57 UTC, IvanAndresFritzler requested changes

2021-12-09 18:58 UTC, eze210 requested changes

2021-12-09 18:58 UTC, eze210 commented on core-tests/src/test/java/org/mule/runtime/core/api/profiling/ProcessingStrategyDataConsumersTestCase.java
> +        throw new RuntimeException();
Add e as the cause

2021-12-13 13:54 UTC, eze210 approved these changes

2021-12-13 15:58 UTC, IvanAndresFritzler approved these changes

2021-12-13 15:59 UTC, merged