EE-7870: Move streaming manager to use memory manager buffers
mulesoft/mule pull request #11238
Opened 2022-01-17 19:08 UTC by IvanAndresFritzler

2022-01-31 09:03 UTC, marianogonzalez requested changes

2022-01-31 09:03 UTC, marianogonzalez commented on core/src/main/java/org/mule/runtime/core/api/streaming/DefaultStreamingManager.java
> +    byteBufferManager.setByteBufferProvider(memoryManagementService.getByteBufferProvider(getByteBufferProviderName(), HEAP));
why keep having the ByteBufferManager at all?  Looks like what the ByteBuferProvider should be able to do everything it does

2022-02-05 22:49 UTC, IvanAndresFritzler commented
--validate

2022-02-05 22:54 UTC, IvanAndresFritzler commented
--validate

2024-07-12 13:28 UTC, closed without merging