MULE-19966: Replace SpringXmlConfigurationBuilder with an ArtifactAstConfigurationBuilder
mulesoft/mule pull request #11242
Opened 2022-01-18 19:52 UTC by elrodro83

2022-01-19 23:50 UTC, elrodro83 commented
--validate

2022-01-20 11:28 UTC, elrodro83 commented
--validate

2022-01-20 12:51 UTC, eze210 requested changes

2022-01-20 12:51 UTC, eze210 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/ArtifactAstConfigurationBuilder.java
> +                                                         ApplicationContext parentContext)
unused param

2022-01-20 12:51 UTC, eze210 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/ArtifactAstConfigurationBuilder.java
> +    if (parentContext != null && parentContext instanceof ComponentModelInitializer) {
instanceof returns false for nulls

2022-01-20 12:51 UTC, eze210 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/ArtifactAstConfigurationBuilder.java
> +    MuleArtifactContext muleArtifactContext;
rename to avoid shadowing the attribute

2022-01-20 12:51 UTC, eze210 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/ArtifactAstConfigurationBuilder.java
> +    ComponentBuildingDefinitionRegistryFactory componentBuildingDefinitionRegistryFactory =
rename to avoid shadowing the attribute

2022-01-20 12:51 UTC, eze210 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/ArtifactAstConfigurationBuilder.java
> +                                                         Optional<ConfigurationProperties> parentConfigurationProperties,
unused param

2022-01-20 12:51 UTC, eze210 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/dsl/artifact/AstArtifactConfigurationProcessor.java
> +                                                                       .map(parentContext -> parentContext.getArtifactAst())
ArtifactContext::getArtifactAst

2022-01-20 12:51 UTC, eze210 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/dsl/artifact/AstArtifactConfigurationProcessor.java
> +        break;
Exception? Warning?

2022-01-20 12:51 UTC, eze210 commented on modules/spring-config/src/test/java/org/mule/runtime/config/internal/AstArtifactConfigurationProcessorTestCase.java
> +  }
Add some assertion

2022-01-20 12:51 UTC, eze210 commented on tests/functional/src/main/java/org/mule/functional/junit4/AbstractConfigurationFailuresTestCase.java
> +      muleContext.start();
If start() fails, is it correct to call stop()?

2022-01-20 14:24 UTC, eze210 approved these changes

2022-01-20 16:21 UTC, merged