MULE-20054: Optimize decoration of input streams
mulesoft/mule pull request #11252
Opened 2022-01-20 00:27 UTC by asanguinetti

2022-01-20 14:37 UTC, fsgonz approved these changes

2022-01-20 14:37 UTC, fsgonz commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/internal/runtime/execution/MethodArgumentResolverDelegate.java
> +    } else if (Object.class.equals(argumentType)) {
MULE-17903 to verify why this was done, as indicated in the PR full explanation.

2022-01-20 14:54 UTC, marianogonzalez requested changes
This solution is trying to optimize #9234 . The problem is that had I seen that PR originally, I woudl have rejected it:

1) The entire solution is entirely based on specific resolvers of the Java SDK. This means that it won't work any of the other SDK flavours 
2) It's based on introspecting the extension's code. It should instead be inspecting the resulting ExtensionModel.
3) it forces adding similar logic for sources, functions, etc. This should all be centralized on the returning piece of it, not on each usage.
4) it forces propagating concepts such as content to components that should not have it

The correct solution here is to revert #9234 and reimplement it completely. This solution does not scale and does not align with the refactors we're doing in the SDK to do reuse. Please write/refer to a spec in which the design for this was discussed.

Thank you

2022-01-20 14:54 UTC, marianogonzalez commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/api/loader/java/type/ExtensionParameter.java
> +  default boolean isContent() {
this shouldn't be done here nor it should depend on the extension code but the extension model

2022-01-26 14:21 UTC, asanguinetti commented
I'm closing this PR because we are going to go with the revert option.

2022-01-26 14:21 UTC, closed without merging