W-10619595: Calculating the blocking condition for Mule Operations.
mulesoft/mule pull request #11376
Opened 2022-03-22 00:05 UTC by asanguinetti

2022-03-22 14:57 UTC, marianogonzalez requested changes

2022-03-22 15:24 UTC, asanguinetti commented on modules/extensions-mule-support/src/main/java/org/mule/runtime/module/extension/mule/internal/loader/parser/MuleSdkOperationModelParserSdk.java
> +  private boolean computeIsBlocking(Map<String, MuleSdkOperationModelParserSdk> operationModelParsersByName) {
I agree, it is ugly. I think I will just set it internally, because I'm using that to also update other inner parsers along the way.

2022-03-23 13:08 UTC, marianogonzalez requested changes

2022-03-23 13:08 UTC, marianogonzalez commented on modules/extensions-mule-support/src/main/java/org/mule/runtime/module/extension/mule/internal/loader/parser/MuleSdkOperationModelParserSdk.java
> +    Preconditions.checkState(isBlocking != null, "Characteristics have not been computed yet.");
static import

2022-03-23 13:37 UTC, marianogonzalez approved these changes

2022-03-23 15:42 UTC, marianogonzalez approved these changes

2022-03-23 16:18 UTC, asanguinetti commented
--validate

2022-03-23 19:07 UTC, asanguinetti commented
--validate

2022-03-23 20:35 UTC, merged