W-10875252: Implement the Unit of Works Extension for the Profiling API
mulesoft/mule pull request #11410
Opened 2022-04-05 15:14 UTC by IvanAndresFritzler

2022-04-05 15:49 UTC, marianogonzalez requested changes

2022-04-05 15:49 UTC, marianogonzalez commented on core/src/main/java/org/mule/runtime/core/internal/profiling/consumer/tracing/span/DefaultSpanDuration.java
> +
shouldn't this be native?

2022-04-05 15:49 UTC, marianogonzalez commented on core/src/main/java/org/mule/runtime/core/internal/profiling/consumer/tracing/span/ExecutionSpan.java
> +    return Optional.ofNullable(parent);
static import

2022-04-05 17:44 UTC, fsgonz approved these changes

2022-04-06 12:48 UTC, marianogonzalez requested changes

2022-04-06 15:57 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/consumer/tracing/span/DefaultSpanDuration.java
> +    this.endTime = endTime;
I think that only receiving the start timestamp is better given how things ended up being implemented. At the beginning. I will modify it to something like your suggestion.

2022-04-06 16:05 UTC, marianogonzalez commented on core/src/main/java/org/mule/runtime/core/internal/profiling/consumer/tracing/span/DefaultSpanDuration.java
> +    this.endTime = endTime;
Cool. Note however that my comment intends to go beyond the constructor but the overall design choices of what should be immutable and what shouldn't. Regardless of the constructor and inner representation, when you do end the span the duration instance gets overriden. The ask is to re-evaluate but most importantly document that design choice.

2022-04-06 17:02 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/consumer/tracing/span/DefaultSpanDuration.java
> +    this.endTime = endTime;
I will add more detail about this to the SPEC.

2023-03-16 18:43 UTC, closed without merging