W-10719167: XML SDK modules cannot access configs defined at the domain level.
mulesoft/mule pull request #11411
Opened 2022-04-06 18:07 UTC by SebaElizalde

2022-04-12 13:46 UTC, SebaElizalde commented
--validate

2022-04-12 17:36 UTC, ndinu requested changes

2022-04-12 17:36 UTC, ndinu commented on modules/extensions-xml-support/src/main/java/org/mule/runtime/extension/internal/ast/MacroExpansionModuleModel.java
> +              .orElseGet(() -> { // Else look for the element in the parent ast (e.g. the domain of the app)
Should this be recursive? Or just check 1 level ?

2022-04-12 17:36 UTC, ndinu commented on modules/extensions-xml-support/src/main/java/org/mule/runtime/extension/internal/ast/MacroExpansionModuleModel.java
> +                  return parent.get()
I think that the whole condition/processing should be modularized so that the code to check the app and the domain is not duplicated.

2022-04-13 17:29 UTC, ndinu approved these changes

2022-04-13 17:48 UTC, merged