Avoid duplicating error handlers when referencing a global error handler
mulesoft/mule pull request #11434
Opened 2022-04-20 13:01 UTC by marianorean

2022-05-04 17:50 UTC, marianorean commented
--validate

2022-05-04 18:04 UTC, fsgonz commented on core/src/main/java/org/mule/runtime/core/privileged/exception/OnRuntimeProcessingStrategy.java
> +  private String getFlowName(CoreEvent e) {
getFlowName -> getParentFlowNameForErrorHandler

2022-05-04 18:13 UTC, fsgonz commented on core/src/main/java/org/mule/runtime/core/privileged/exception/OnRuntimeProcessingStrategy.java
>  public class OnRuntimeProcessingStrategy implements ProcessingStrategy {
This should have been present in the previous review:

add a javadoc for this, maybe like this.
/**
 * A {@link ProcessingStrategy} used for {@link org.mule.runtime.core.internal.exception.GlobalErrorHandler}.
 * The resolution of the processing strategy is done in runtime depending on the flow location where the
 * error that is being handled was thrown.
 */

2022-05-04 18:25 UTC, fsgonz requested changes

2022-05-04 18:25 UTC, fsgonz commented on core/src/main/java/org/mule/runtime/core/privileged/exception/OnRuntimeProcessingStrategy.java
> +    if (logger.isDebugEnabled()) {
I don't understand this. Is this always logged?

2022-05-05 19:18 UTC, fsgonz approved these changes
Verify if the injection of the feature flag works ok. I think this should fail in some test anyway.

2022-05-05 19:36 UTC, merged