W-11090837: Migrate HttpListenerBindTestCase to unit test
mulesoft/mule pull request #11460
Opened 2022-05-05 20:57 UTC by sofiamorseletto

2022-05-09 12:18 UTC, sofiamorseletto commented
--validate

2022-05-09 20:38 UTC, sofiamorseletto commented
--validate

2022-05-10 17:10 UTC, elrodro83 requested changes

2022-05-10 17:10 UTC, elrodro83 commented on modules/deployment/src/test/java/org/mule/runtime/module/deployment/logging/LoggingAppStartErrorTestCase.java
> +  }
use expected rule instead, with the assertions in a finally block

2022-05-10 17:10 UTC, elrodro83 commented on modules/deployment/src/test/java/org/mule/runtime/module/deployment/logging/LoggingAppStartErrorTestCase.java
> +    String expectedLogMessage = "Could not start HTTP server for 'lisConfig' on port 27664: Address already in use";
make this message something that explicitely indicates what is happening instead of this http-ish error message.

2022-05-12 20:11 UTC, elrodro83 approved these changes

2022-05-16 12:49 UTC, merged