fix
mulesoft/mule pull request #11475
Opened 2022-05-16 19:41 UTC by eze210

2022-05-17 13:19 UTC, eze210 commented
--validate

2022-05-20 09:11 UTC, marianogonzalez requested changes

2022-05-20 09:11 UTC, marianogonzalez commented on modules/extensions-mule-support/pom.xml
> +            <version>1.0.0-SNAPSHOT</version>
property or depManagement

2022-05-20 12:33 UTC, elrodro83 requested changes

2022-05-20 12:33 UTC, elrodro83 commented on modules/extensions-mule-support/src/test/java/org/mule/runtime/module/extension/mule/internal/operation/MuleOperationProcessingStrategyTestCase.java
> +import static org.mule.test.allure.AllureConstants.ReuseFeature.ReuseStory.OPERATIONS;
mule imports go first

2022-05-20 12:33 UTC, elrodro83 commented on modules/extensions-mule-support/src/test/java/org/mule/runtime/module/extension/mule/internal/operation/MuleOperationProcessingStrategyTestCase.java
> +  private Integer getExecutionThreadPhase(String key) {
wouldn't this be `getExecutionThreadForPhase` better?

2022-05-20 12:33 UTC, elrodro83 commented on modules/extensions-mule-support/src/test/java/org/mule/runtime/module/extension/mule/internal/operation/MuleOperationProcessingStrategyTestCase.java
> +  private Integer getCompletionThreadPhase(String key) {
wouldn't this be `getCompletionThreadForPhase` better?

2022-05-20 12:33 UTC, elrodro83 commented on modules/extensions-mule-support/src/test/java/org/mule/runtime/module/extension/mule/internal/operation/MuleOperationProcessingStrategyTestCase.java
> +  private Integer getCompletionThreadPhase(String key) {
remove the `get` prefix as well

2022-05-20 12:33 UTC, elrodro83 commented on modules/extensions-mule-support/src/test/java/org/mule/runtime/module/extension/mule/internal/operation/MuleOperationProcessingStrategyTestCase.java
> +  private Integer getExecutionThreadPhase(String key) {
remove the `get` prefix as well

2022-05-20 12:33 UTC, elrodro83 commented on modules/extensions-mule-support/src/test/java/org/mule/runtime/module/extension/mule/internal/operation/MuleOperationProcessingStrategyTestCase.java
> +    assertThat(blockingOpExecutionPhase, is(nextOpExecutionPhase));
i think that this will be more readable by inlining the Integer vars and the other changes at the bottom of this class.

2022-05-20 12:33 UTC, elrodro83 commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/internal/runtime/operation/construct/MuleOperation.java
> +    processingStrategy = getDefaultProcessingStrategyFactory(muleContext).create(muleContext, operationModel.getName());
are there tasks to make this consistent with other places where chains are created?

2022-05-20 15:22 UTC, elrodro83 approved these changes

2022-05-20 15:38 UTC, marianogonzalez approved these changes

2022-05-20 15:38 UTC, merged