W-10619592: implement the supportsStreaming() method for Mule Operations
mulesoft/mule pull request #11492
Opened 2022-05-24 10:36 UTC by mbuchwald

2022-05-25 09:58 UTC, mbuchwald commented
--validate

2022-05-30 13:03 UTC, asanguinetti requested changes
Besides the requested changes, was `modules/salida.txt` commited by mistake?

2022-05-30 13:03 UTC, asanguinetti commented on modules/extensions-mule-support/src/test/java/org/mule/runtime/module/extension/mule/internal/operation/MuleOperationSupportsStreamingTestCase.java
> +public class MuleOperationSupportsStreamingTestCase extends MuleArtifactFunctionalTestCase {
Add Allure annotations, for the test case and for the tests.

2022-05-30 15:28 UTC, asanguinetti approved these changes

2022-05-30 16:03 UTC, asanguinetti approved these changes

2022-05-30 18:10 UTC, mbuchwald commented
--validate

2022-05-31 13:22 UTC, merged