Make ExtensionModelDiscoverer#discoverRuntimeExtensionModels static
mulesoft/mule pull request #11516
Opened 2022-06-06 18:32 UTC by jcgrethe

2022-06-07 14:59 UTC, jcgrethe commented
--validate

2022-06-07 17:44 UTC, jcgrethe commented
--validate

2022-06-08 02:35 UTC, jcgrethe commented
--validate

2022-06-08 17:57 UTC, rbourbonnavarro submitted a review, later dismissed

2022-06-08 18:01 UTC, elrodro83 requested changes

2022-06-08 18:01 UTC, elrodro83 commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/extension/discovery/DefaultExtensionModelDiscoverer.java
> +                         .addAll(ExtensionModelDiscoverer.discoverRuntimeExtensionModels())
static import

2022-06-08 20:06 UTC, elrodro83 approved these changes

2022-06-09 13:34 UTC, merged