W-10877267: A.11.2 Implement the automatic propagation of trace context
mulesoft/mule pull request #11583
Opened 2022-07-05 14:11 UTC by fsgonz

2022-07-12 15:31 UTC, marianogonzalez requested changes

2022-07-12 15:31 UTC, marianogonzalez commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/internal/runtime/parameter/PropagateAllDistributedTraceContextManager.java
> +    return contextMap;
should use unmodifiableMap() here?

2022-07-13 13:16 UTC, fsgonz commented on core/src/main/java/org/mule/runtime/core/internal/event/AbstractEventContext.java
> +abstract class AbstractEventContext implements DistributedTraceContextAware, BaseEventContext {
BaseContext is a privileged interface. I would rather not change anything related to api (even privileged apis), as this is only used internally.

2022-07-13 15:58 UTC, marianogonzalez requested changes

2022-07-13 15:58 UTC, marianogonzalez commented on core/src/main/java/org/mule/runtime/core/internal/event/DefaultEventContext.java
> +  public DistributedTraceContext getDistributedTraceContext() {
are these two missing an `@Override`?

2022-07-13 15:58 UTC, marianogonzalez commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/internal/runtime/parameter/PropagateAllDistributedTraceContextManager.java
> +    contextMap = unmodifiableMap(distributedTraceContext.baggageItemsAsMap());
is this change correct? It seems like previously you were also including the tracing fields but not anymore. Which version is boggus?

2022-07-14 12:32 UTC, marianogonzalez approved these changes

2022-07-14 12:32 UTC, merged