W-11410177: Refactor: the current span should travel with the event
mulesoft/mule pull request #11613
Opened 2022-07-18 12:15 UTC by fsgonz

2022-07-18 15:04 UTC, fsgonz commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/span/CoreEventExecutionSpanProvider.java
> + */
This should be a customizer of each attribute of the span (eventually increment it), not the creation of the span.

2022-07-19 16:33 UTC, IvanAndresFritzler requested changes

2022-07-19 16:33 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/DefaultProfilingService.java
> +  private MuleCoreEventTracer eventTracer;
Rename to CoreEventTracer

2022-07-19 16:33 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/DefaultProfilingService.java
> +  private void createMuleEventTracer() {
rename to createCoreEventTracer

2022-07-19 16:33 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/DefaultProfilingService.java
> +    this.eventTracer = getMuleEventTracerBuilder()
Rename to getCoreEventTracerBuilder

2022-07-19 16:33 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/DefaultProfilingService.java
> +        .withDefaultCoreEventExecutionSpanProvider(getMuleDefaultCoreEventExecutionSpanProvider())
Rename to getDefaultCoreEventExecutionSpanProvider

2022-07-19 16:33 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/DefaultProfilingService.java
> +  public MuleCoreEventTracer getMuleCoreEventTracer() {
rename to getCoreEventTracer

2022-07-19 16:33 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/NoOpProfilingService.java
> +    public InternalSpan startComponentExecutionSpan(CoreEvent coreEvent, Component component) {
Rename to startComponentSpan

2022-07-19 16:33 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/NoOpProfilingService.java
> +                                                    CoreEventSpanCustomizer coreEventSpanCustomizer) {
Rename to startComponentSpan

2022-07-19 16:33 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/tracer/MuleCoreEventTracer.java
> +public interface MuleCoreEventTracer {
Rename to CoreEventTracer

2022-07-19 16:33 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/span/CoreEventSpanUtils.java
> +  public static Optional<InternalSpan> getCurrentContextSpan(EventContext eventContext) {
Rename to getCurrentSpan

2022-07-19 16:33 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/span/CoreEventSpanUtils.java
> +  public static String getCoreEventSpanName(ComponentIdentifier componentIdentifier) {
Rename to getSpanName

2022-07-19 16:33 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/span/CoreEventExecutionSpanProvider.java
> +public interface CoreEventExecutionSpanProvider {
Rename to CoreEventSpanProvider or CoreEventSpanFactory

2022-07-19 16:33 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/tracer/impl/DefaultMuleCoreEventTracer.java
> +public class DefaultMuleCoreEventTracer implements MuleCoreEventTracer {
Rename to DefaultCoreEventTracer

2022-07-19 16:33 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/tracer/impl/DefaultMuleCoreEventTracer.java
> +    return setCurrentContextSpanInEventContextIfPossible(coreEvent,
Rename to setCurrentSpanIfPossible

2022-07-19 16:33 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/tracer/impl/DefaultMuleCoreEventTracer.java
> +  private void endCurrentContextSpanIfPosibble(CoreEvent coreEvent) {
Rename to endCurrentSpanIfPossible

2022-07-19 19:24 UTC, IvanAndresFritzler requested changes

2022-07-19 19:24 UTC, IvanAndresFritzler commented on core-tests/src/test/java/org/mule/runtime/core/internal/profiling/consumer/tracing/DefaultMuleCoreEventTracerTestCase.java
> +@Story(DEFAULT_MULE_CORE_EVENT_TRACER)
Rename to DEFAULT_CORE_EVENT_TRACER

2022-07-19 19:24 UTC, IvanAndresFritzler commented on core-tests/src/test/java/org/mule/runtime/core/internal/profiling/consumer/tracing/DefaultMuleCoreEventTracerTestCase.java
> +public class DefaultMuleCoreEventTracerTestCase {
Rename to DefaultCoreEventTracerTestCase

2022-07-19 19:24 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/execution/FlowProcessMediator.java
> +  private CoreEventTracer muleEventTracer;
Rename to eventTracer

2022-07-19 19:24 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/NoOpProfilingService.java
> +  private CoreEventTracer muleCoreEventTracer = new NoOpCoreEventTracer();
Rename to eventTracer

2022-07-19 19:24 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/OpentelemetryExecutionSpan.java
> +public class OpentelemetryExecutionSpan implements InternalSpan {
Rename to OpenTelemetrySpan

2022-07-19 19:24 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/span/CoreEventSpanUtils.java
> +  public static CoreEventSpanFactory getMuleDefaultCoreEventExecutionSpanProvider() {
Rename to getDefaultCoreEventSpanFactory

2022-07-19 19:24 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/tracer/impl/DefaultCoreEventTracer.java
> +  private final CoreEventSpanFactory defaultCoreEventExecutionSpanProvider;
Rename to defaultCoreEventSpanFactory

2022-07-19 19:24 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/tracer/impl/DefaultCoreEventTracer.java
> +    private CoreEventSpanFactory coreEventExecutionSpanProvider;
Rename to coreEventSpanFactory

2022-07-19 19:24 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/tracer/impl/DefaultCoreEventTracer.java
> +    public DefaultEventTracerBuilder withDefaultCoreEventExecutionSpanProvider(
rename to withDefaultCoreEventSpanFactory

2022-07-19 19:24 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/tracer/impl/DefaultCoreEventTracer.java
> +    endCurrentContextSpanIfPosibble(coreEvent);
rename to endCurrentSpanIfPossible

2022-07-19 19:24 UTC, IvanAndresFritzler commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/tracer/impl/DefaultCoreEventTracer.java
> +          .endCurrentContextSpan();
rename to getCurrentSpan

2022-07-20 13:33 UTC, IvanAndresFritzler approved these changes

2022-07-20 13:58 UTC, merged