W-11464483: Raise Error usage within a reusable Mule Operation
mulesoft/mule pull request #11652
Opened 2022-08-05 01:37 UTC by eze210

2022-08-05 17:48 UTC, eze210 commented
--validate

2022-08-05 19:52 UTC, eze210 commented
--validate

2022-08-05 21:13 UTC, eze210 commented
--validate

2022-08-05 22:37 UTC, eze210 commented
--validate

2022-08-08 13:30 UTC, asanguinetti requested changes

2022-08-08 13:30 UTC, asanguinetti commented on modules/extensions-mule-support/src/main/java/org/mule/runtime/module/extension/mule/api/processor/MuleSdkRaiseErrorProcessor.java
> +    return builder().namespace("THIS").name(typeId).build();
Have we checked what would happen if someone tries to do something like this?
`<operation:raise-error type="THIS:CUSTOM" />`
Or even:
`<operation:raise-error type="OTHER:CUSTOM" />`

Shouldn't we have a test for those cases showing the expected outcome (maybe error in both, or maybe ignoring the namespace in the first one)?

2022-08-08 13:35 UTC, asanguinetti commented on modules/extensions-mule-support/src/main/java/org/mule/runtime/module/extension/mule/api/processor/MuleSdkRaiseErrorProcessor.java
> +    return builder().namespace("THIS").name(typeId).build();
Also, we should probably extract the string "THIS" to a shared constant so can track its usages more easily.
Maybe making this one public or moving it to a constants class: https://github.com/mulesoft/mule/blob/eb7c7bb88896929865674e4f36aed563311ff565/modules/extensions-mule-support/src/main/java/org/mule/runtime/module/extension/mule/internal/loader/parser/MuleSdkExtensionModelParser.java#L55

2022-08-08 18:42 UTC, eze210 commented
--validate

2022-08-08 19:21 UTC, eze210 commented
--validate

2022-08-08 19:39 UTC, eze210 commented
--validate

2022-08-08 23:32 UTC, eze210 commented
--validate

2022-08-09 13:40 UTC, asanguinetti approved these changes

2022-08-09 13:40 UTC, merged