W-11468826: Mule SDK ExtensionModelDeclarer.
mulesoft/mule pull request #11725
Opened 2022-09-06 01:18 UTC by asanguinetti

- Also adding XSD definition.
- Also adding DslNamespaceInfoProvider.
- Also adding ExtensionModelProvider.
- Also adding RuntimeExtensionModelProvider.

2022-09-06 20:13 UTC, eze210 requested changes

2022-09-06 20:13 UTC, eze210 commented on modules/extensions-mule-support/src/main/java/org/mule/runtime/module/extension/mule/api/extension/MuleSdkExtensionExtensionModelDeclarer.java
> +    final BaseTypeBuilder typeBuilder = BaseTypeBuilder.create(JavaTypeLoader.JAVA);
static imports

2022-09-06 20:13 UTC, eze210 commented on modules/extensions-mule-support/src/main/java/org/mule/runtime/module/extension/mule/api/extension/MuleSdkExtensionRuntimeExtensionModelProvider.java
> +
blank

2022-09-06 20:13 UTC, eze210 commented on modules/extensions-mule-support/src/main/java/org/mule/runtime/module/extension/mule/api/extension/MuleSdkExtensionRuntimeExtensionModelProvider.java
> +
blank

2022-09-06 20:13 UTC, eze210 commented on modules/extensions-mule-support/src/main/java/org/mule/runtime/module/extension/mule/internal/dsl/processor/xml/MuleSdkExtensionDslNamespaceInfoProvider.java
> +    return asList(new XmlNamespaceInfo() {
Maybe singletonList since it's only one element (and remove blank)

2022-09-06 20:13 UTC, eze210 commented on modules/extensions-mule-support/src/test/java/org/mule/runtime/module/extension/mule/api/extension/MuleExtensionExtensionModelTestCase.java
> +    expectedParameters.put("vendor", is(Extension.MULESOFT));
static import

2022-09-06 20:13 UTC, eze210 commented on modules/extensions-mule-support/src/test/java/org/mule/runtime/module/extension/mule/api/extension/MuleExtensionExtensionModelTestCase.java
> +    for (Map.Entry<String, Matcher<Object>> entry : expectedParameters.entrySet()) {
statically import Entry

2022-09-06 20:29 UTC, eze210 approved these changes

2022-09-07 08:35 UTC, marianogonzalez requested changes

2022-09-07 08:35 UTC, marianogonzalez commented on modules/extensions-mule-support/src/main/java/org/mule/runtime/module/extension/mule/api/extension/MuleSdkExtensionExtensionModelProvider.java
> +    context.addParameter(FORCE_EXTENSION_VALIDATION_PROPERTY_NAME, true);
why?

2022-09-07 12:32 UTC, asanguinetti commented on modules/extensions-mule-support/src/main/java/org/mule/runtime/module/extension/mule/api/extension/MuleSdkExtensionExtensionModelProvider.java
> +    context.addParameter(FORCE_EXTENSION_VALIDATION_PROPERTY_NAME, true);
Honestly I forgot to ask about this one.
I took it trying to mimick what we did for the [OperationDslExtensionModelProvider](https://github.com/mulesoft/mule/blob/9c92460a7a3bb39d6eccbc42a6bb65d3662d8785/core/src/main/java/org/mule/runtime/core/api/extension/OperationDslExtensionModelProvider.java#L22), which in turn delegates to [this](https://github.com/mulesoft/mule/blob/9c92460a7a3bb39d6eccbc42a6bb65d3662d8785/runtime-extension-model/src/main/java/org/mule/runtime/core/api/extension/MuleExtensionModelProvider.java#L94).
I assumed this one should be similar, but I had to check what that property does and I forgot. Let me see if I can find out quickly.

2022-09-07 13:15 UTC, asanguinetti commented on modules/extensions-mule-support/src/main/java/org/mule/runtime/module/extension/mule/api/extension/MuleSdkExtensionExtensionModelProvider.java
> +    context.addParameter(FORCE_EXTENSION_VALIDATION_PROPERTY_NAME, true);
I was tracking it and seems it is only used for deciding if [this code](https://github.com/mulesoft/mule-extensions-api/blob/84712b1dbc09ed0df586fc6f0dd43088a7985b82/mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/ExtensionModelFactory.java#L225) should execute.
Which is basically running the validators defined [here](https://github.com/mulesoft/mule-extensions-api/blob/84712b1dbc09ed0df586fc6f0dd43088a7985b82/mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/ExtensionModelFactory.java#L190) (and also any custom ones which for this case there are none) against the ExtensionModel that is being created.
Apparently, the default is to not run the validations.
It was added to the `MuleExtensionModelProvider` as part of [this change](https://github.com/mulesoft/mule/commit/1723401c53a5400b7547fc8da0e79faf06779cba#diff-92c3b537c785fb24eeb4f03e894071b91c10fce569a81072629c0440fcca8dbfR94) which was part of the PoC for the Application ExtensionModel.
I suppose the `ExtensionModel` for the `extension` namespace should be affected by the same criteria we used for the `operation` namespace.
Intuitively it makes sense to validate even our own hand-crafted models, just to make sure they are consistent with all the rules. If we are concerned about performance we could validate them as part of the `mvn validate` goal of the corresponding Maven module instead of doing it in runtime during deployment. But that change would be out of scope for this PR.

2022-09-07 13:56 UTC, marianogonzalez approved these changes
conditional approve

2022-09-07 14:08 UTC, asanguinetti commented on modules/extensions-mule-support/src/main/java/org/mule/runtime/module/extension/mule/api/extension/MuleSdkExtensionExtensionModelProvider.java
> +    context.addParameter(FORCE_EXTENSION_VALIDATION_PROPERTY_NAME, true);
After following up in Slack, we agreed that this property should be removed from all places in which we are creating our own extension models.
The validation should already be happening during testing because of [this](https://github.com/mulesoft/mule-extensions-api/blob/84712b1dbc09ed0df586fc6f0dd43088a7985b82/mule-extensions-api/src/main/java/org/mule/runtime/extension/internal/loader/ExtensionModelFactory.java#L207). We should not do it in runtime then.
I created another work item ([W-11719146](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000015uqwdYAA/view)) to track the removal of the property and verifying that the validations are run when testing. Hence, we will be leaving it out of the scope of this particular PR.

2022-09-07 14:09 UTC, merged