W-11584645: Add a mechanism to ignore levels in hierarchy of spans
mulesoft/mule pull request #11756
Opened 2022-09-14 19:28 UTC by fsgonz

2022-09-15 13:00 UTC, fsgonz commented
--validate

2022-09-16 15:10 UTC, IvanAndresFritzler requested changes

2022-09-16 15:25 UTC, fsgonz commented on core-tests/src/test/java/org/mule/runtime/core/internal/profiling/consumer/tracing/DefaultCoreEventTracerTestCase.java
> +  public void testStartComponentExecution2() {
yes 😱

2022-09-16 15:58 UTC, IvanAndresFritzler submitted a review, later dismissed

2022-09-16 16:18 UTC, IvanAndresFritzler approved these changes

2022-09-16 16:20 UTC, IvanAndresFritzler submitted a review, later dismissed

2022-09-19 15:12 UTC, sofiamorseletto commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/export/InternalSpanExporterVisitor.java
> +   * @return the result of visiting the instnce.
instance*

2022-09-19 15:13 UTC, sofiamorseletto commented on core/src/main/java/org/mule/runtime/core/internal/profiling/tracing/event/span/export/optel/OpentelemetrySpanExporterManager.java
> +  private static final OpentelemetryCoreEventInternalSpanExporterFactory SPAN_EXPORTER_FACTORY =
Shouldn't it be OpenTelemetry... ? Both here as in getOpentelemetryCoreEventInternalSpanExporterFactory

2022-09-19 16:57 UTC, merged