W-11086425: move MuleDeployableProjectModelBuilder to artifact-activa…
mulesoft/mule pull request #11889
Opened 2022-10-19 14:53 UTC by jcgrethe

…tion

2022-10-19 16:30 UTC, jcgrethe commented
--validate

2022-10-19 19:06 UTC, elrodro83 requested changes

2022-10-19 19:06 UTC, elrodro83 commented on modules/deployment-model-impl/src/main/java/org/mule/runtime/module/deployment/impl/internal/artifact/MuleDeployableProjectModelBuilder.java
> +public class MuleDeployableProjectModelBuilder
this is internal, can't this just be removed?

2022-11-02 19:11 UTC, jcgrethe commented
--validate

2022-11-03 17:59 UTC, elrodro83 approved these changes

2022-11-04 17:32 UTC, jcgrethe commented
--validate

2022-11-08 20:15 UTC, elrodro83 requested changes

2022-11-08 20:15 UTC, elrodro83 commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/plugin/PluginClassLoaderConfigurationAssembler.java
> +      throw new MuleRuntimeException(createStaticMessage("There is more than 1 PluginPatchesResolver implementation registered"));
add the found items to the exception message

2022-11-08 20:15 UTC, elrodro83 commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/plugin/MuleArtifactPatchingModel.java
> +public class MuleArtifactPatchingModel {
where is this used? can it be moved along to retain its current visibility?

2022-11-08 20:15 UTC, elrodro83 commented on modules/deployment-model-impl/src/test/java/org/mule/runtime/module/deployment/impl/internal/application/DefaultLightweightApplicationFactoryTestCase.java
> +@Issue("W-11086334")
add the lightweight stroy

2022-11-08 20:15 UTC, elrodro83 commented on modules/deployment-model-impl/src/test/java/org/mule/runtime/module/deployment/impl/internal/domain/DefaultLightweightDomainFactoryTestCase.java
> +public class DefaultLightweightDomainFactoryTestCase extends AbstractMuleTestCase {
add lightweight story

2022-11-08 20:15 UTC, elrodro83 commented on modules/deployment-model-impl/src/test/java/org/mule/runtime/module/deployment/impl/internal/plugin/DeployableDescriptorsWithPatchedPluginsTestCase.java
>  @Story(PATCHED_ARTIFACT_DESCRIPTORS)
add feature

2022-11-08 20:40 UTC, elrodro83 approved these changes

2022-11-09 12:04 UTC, jcgrethe commented
--validate

2022-11-11 00:10 UTC, merged