W-11858321: More refactor on APIs and correction in exports
mulesoft/mule pull request #11903
Opened 2022-10-26 17:56 UTC by mbuchwald

2022-10-26 18:17 UTC, elrodro83 requested changes

2022-10-26 18:17 UTC, elrodro83 commented on modules/metadata-support/src/main/java/org/mule/runtime/metadata/internal/generation/GenerationUtils.java
> +public class GenerationUtils {
add javadoc, with `@since`

2022-10-26 18:17 UTC, elrodro83 commented on modules/metadata-support/src/main/java/org/mule/runtime/metadata/internal/generation/GenerationUtils.java
> +package org.mule.runtime.metadata.internal.generation;
why `generation` instead of `cache`?

2022-10-27 19:01 UTC, elrodro83 submitted a review, later dismissed

2022-10-28 15:58 UTC, mbuchwald commented
--validate

2022-10-28 17:01 UTC, mbuchwald commented
--validate

2022-10-28 18:44 UTC, elrodro83 approved these changes

2022-10-28 18:47 UTC, merged