W-11416423: Error declaration for extensions built with the Mule SDK
mulesoft/mule pull request #11914
Opened 2022-10-31 20:29 UTC by eze210

2022-11-02 18:58 UTC, asanguinetti requested changes
Partial review. Some minor things.

2022-11-02 19:18 UTC, eze210 commented on modules/extensions-mule-support/src/test/resources/extensions/extension-with-errors.xml
> +           xmlns:core="http://www.mulesoft.org/schema/mule/core"
I like it more with core

2022-11-02 19:18 UTC, eze210 commented on modules/extensions-mule-support/src/test/java/org/mule/runtime/module/extension/mule/internal/loader/ExtensionModelTestUtils.java
> +   * @param dependencies   classLoader to be used to load the plugin.
Done

2022-11-02 19:18 UTC, eze210 commented on modules/extensions-mule-support/src/test/java/org/mule/runtime/module/extension/mule/internal/loader/ExtensionModelTestUtils.java
> +                                                    Set<ExtensionModel> astParserExtensionModels) {
Added both versions of the method. We had a test that needed to specify the classloader

2022-11-02 19:42 UTC, asanguinetti approved these changes

2022-11-02 21:03 UTC, asanguinetti approved these changes

2022-11-03 12:39 UTC, eze210 commented
--validate

2022-11-03 14:05 UTC, merged