W-11203142: Descriptors generation API: include test dependencies and resources when needed
mulesoft/mule pull request #11977
Opened 2022-11-22 16:52 UTC by rbourbonnavarro

2022-11-22 17:20 UTC, elrodro83 requested changes

2022-11-22 17:20 UTC, elrodro83 commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/maven/AbstractMavenDeployableProjectModelBuilder.java
> +  protected AbstractMavenDeployableProjectModelBuilder(MavenConfiguration mavenConfiguration, File projectFolder) {
wouldn't this break places where this is already extended?

2022-11-22 17:20 UTC, elrodro83 commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/maven/AbstractMavenDeployableProjectModelBuilder.java
> +  public DeployableProjectModel build() {
how is this relevant to the feature being added?

2022-11-22 17:20 UTC, elrodro83 commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/maven/AbstractMavenDeployableProjectModelBuilder.java
> +  protected <T> T getSimpleAttribute(Map<String, Object> attributes, String attribute, T defaultValue) {
is this ok to be protected?

2022-11-22 17:30 UTC, elrodro83 requested changes

2022-11-22 17:30 UTC, elrodro83 commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/maven/AbstractMavenDeployableProjectModelBuilder.java
> +  protected <T> T getSimpleAttribute(Map<String, Object> attributes, String attribute, T defaultValue) {
make final

2022-11-22 17:30 UTC, elrodro83 commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/maven/AbstractMavenDeployableProjectModelBuilder.java
> +  protected List<String> getAttribute(Map<String, Object> attributes, String attribute) {
make final

2022-11-22 17:30 UTC, elrodro83 commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/maven/AbstractMavenDeployableProjectModelBuilder.java
> +  public DeployableProjectModel build() {
make final?

2022-11-22 19:48 UTC, elrodro83 approved these changes

2022-11-22 22:42 UTC, rbourbonnavarro commented
--validate

2022-11-24 12:57 UTC, rbourbonnavarro commented
--validate

2022-11-24 21:01 UTC, rbourbonnavarro commented
--validate

2022-11-25 12:37 UTC, merged