W-12075637: Separate modules in well defined levels for the tracing configurations
mulesoft/mule pull request #11979
Opened 2022-11-23 12:54 UTC by fsgonz

2022-11-26 00:26 UTC, fsgonz commented
--validate

2022-11-28 14:26 UTC, fsgonz commented
--validate

2022-11-28 15:14 UTC, sofiamorseletto commented on core/src/main/java/org/mule/runtime/core/api/tracing/customization/NoExportTillExecuteNextComponentCoreInfoProviderStart.java
> +public class NoExportTillExecuteNextComponentCoreInfoProviderStart extends ComponentCoreStartSpanInfoProvider {
Is the "Start" correctly placed?

2022-11-28 15:15 UTC, sofiamorseletto commented on core/src/main/java/org/mule/runtime/core/api/tracing/customization/FixedNameStartSpanInfo.java
> + * A {@link StartSpanInfo} with a fix name.
fixed*

2022-11-28 15:19 UTC, sofiamorseletto commented on core/src/main/java/org/mule/runtime/core/api/tracing/customization/NoExportableNoExportableFixedNameCoreSpanCustomizationInfoProvider.java
> +  public NoExportableNoExportableFixedNameCoreSpanCustomizationInfoProvider(String name) {
"NoExportable" is duplicated right?

2022-11-28 15:24 UTC, sofiamorseletto commented on core/src/main/java/org/mule/runtime/core/api/tracing/customization/NoFixedNameSpanCustomizationInfo.java
> +public class NoFixedNameSpanCustomizationInfo extends FixedNameStartSpanInfo {
Could we add a Javadoc to this class?

2022-11-28 16:08 UTC, IvanAndresFritzler requested changes

2022-11-28 16:08 UTC, IvanAndresFritzler commented on modules/tracing/mule-tracer-exporter-impl/src/main/java/org/mule/runtime/tracer/impl/exporter/DecoratedMuleOpenTelemetrySpan.java
> +import org.mule.runtime.api.profiling.tracing.SpanError;
Order of the imports

2022-11-28 16:08 UTC, IvanAndresFritzler commented on modules/tracing/mule-tracer-exporter-impl/src/main/java/org/mule/runtime/tracer/impl/exporter/NoopMuleOpenTelemetrySpan.java
> +import org.mule.runtime.tracer.api.span.InternalSpan;
Order of the imports

2022-11-28 16:08 UTC, IvanAndresFritzler commented on modules/tracing/mule-tracer-exporter-impl/src/main/java/org/mule/runtime/tracer/impl/exporter/OpenTelemetryResources.java
> +import org.mule.runtime.tracer.api.sniffer.ExportedSpanSniffer;
Order of the imports.

2022-11-28 16:25 UTC, IvanAndresFritzler submitted a review, later dismissed

2022-11-28 16:35 UTC, IvanAndresFritzler approved these changes

2022-11-28 17:29 UTC, sofiamorseletto commented on core/src/main/java/org/mule/runtime/core/privileged/processor/chain/AbstractMessageProcessorChain.java
> +      startSpanInfo = new NoExportFixedNameEventBasedStartSpanInfoProvider("unknown").get(event);
Extract "unknown" to constant indicating what it stands for

2022-11-28 17:29 UTC, sofiamorseletto commented on core/src/main/java/org/mule/runtime/core/privileged/processor/chain/DefaultMessageProcessorChainBuilder.java
> +      if (eventBasedStartStartInfoProvider != null) {
Start is duplicated -> eventBasedStartInfoProvider*

2022-11-28 17:29 UTC, sofiamorseletto commented on core/src/main/java/org/mule/runtime/core/privileged/processor/chain/DefaultMessageProcessorChainBuilder.java
> +                                                     EventBasedStartSpanInfoProvider eventBasedStartStartInfoProvider) {
eventBasedStartInfoProvider*

2022-11-28 17:29 UTC, sofiamorseletto commented on core/src/main/java/org/mule/runtime/core/privileged/processor/chain/MessageProcessorChainBuilder.java
> +  default void setCoreSpanCustomizationInfoProvider(EventBasedStartSpanInfoProvider spanCustomizationInfo) {
Could we change spanCustomizationInfo -> spanCustomizationInfoProvider ?

2022-11-28 17:29 UTC, sofiamorseletto commented on modules/core-components/src/main/java/org/mule/runtime/core/internal/routing/FirstSuccessful.java
> +      route.setCoreSpanCustominzationInfoProvider(new SuffixComponentEventBasedStartSpanInfoProvider(this,
setCoreSpanCustomizationInfoProvider*

2022-11-28 17:29 UTC, sofiamorseletto commented on modules/core-components/src/main/java/org/mule/runtime/core/internal/routing/ProcessorRoute.java
> +  public void setCoreSpanCustominzationInfoProvider(EventBasedStartSpanInfoProvider spanCustomizationInfo) {
setCoreSpanCustomizationInfoProvider*

2022-11-28 18:19 UTC, IvanAndresFritzler approved these changes

2022-11-28 19:11 UTC, merged