Build services per suite
mulesoft/mule pull request #12202
Opened 2023-01-26 20:39 UTC by eze210

2023-01-30 14:48 UTC, eze210 commented
--validate

2023-01-30 20:23 UTC, asanguinetti requested changes

2023-01-30 20:23 UTC, asanguinetti commented on modules/deployment/src/test/java/org/mule/runtime/module/deployment/internal/TestServicesSetup.java
> +public class TestServicesSetup extends ExternalResource {
We could add some JavaDoc to this class.

2023-01-30 20:23 UTC, asanguinetti commented on modules/deployment/src/test/java/org/mule/runtime/module/deployment/internal/DomainDeploymentWithELServiceTestCase.java
> +    final File defaultServiceSchedulerJarFile = getResourceFile(weaveJarUrl.getFile(), tempFolder);
We could fix this even further:
```suggestion
    final File defaultServiceJarFile = getResourceFile(weaveJarUrl.getFile(), tempFolder);
```

2023-01-31 13:43 UTC, asanguinetti approved these changes

2023-01-31 15:26 UTC, eze210 commented
--validate

2023-01-31 17:04 UTC, merged