W-12514052: migrate Mule to the new maven API
mulesoft/mule pull request #12288
Opened 2023-03-06 15:30 UTC by jcgrethe

2023-03-08 17:25 UTC, jcgrethe commented
--validate

2023-04-05 14:25 UTC, elrodro83 requested changes

2023-04-05 14:25 UTC, elrodro83 commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/maven/AdditionalPluginDependenciesResolver.java
> +              LinkedList<BundleDescriptor> effectiveDependencies =
declare as `List`

2023-04-05 14:25 UTC, elrodro83 commented on modules/artifact/src/test/java/org/mule/runtime/module/artifact/builder/AbstractDependencyFileBuilder.java
> +    return bundleDependency;
inline the return value

2023-04-05 14:25 UTC, elrodro83 commented on modules/deployment-model-impl/src/main/java/org/mule/runtime/module/deployment/impl/internal/maven/ArtifactClassLoaderConfigurationBuilder.java
> +                                                                                                       MavenPomParser parser) {
same line

2023-04-05 14:25 UTC, elrodro83 commented on modules/deployment-model-impl/src/main/java/org/mule/runtime/module/deployment/impl/internal/maven/ArtifactClassLoaderConfigurationBuilder.java
> +                                                                                                   org.mule.maven.pom.parser.api.model.BundleDescriptor descriptor) {
same line

2023-04-05 14:25 UTC, elrodro83 commented on modules/deployment-model-impl/src/main/java/org/mule/runtime/module/deployment/impl/internal/maven/HeavyweightClassLoaderConfigurationBuilder.java
> +                                                                                                       MavenPomParser parser) {
same line

2023-04-05 14:25 UTC, elrodro83 commented on modules/deployment-model-impl/src/main/java/org/mule/runtime/module/deployment/impl/internal/maven/LightweightClassLoaderConfigurationBuilder.java
> +                                                                                                       MavenPomParser parser) {
same line

2023-04-05 14:25 UTC, elrodro83 commented on modules/deployment-model-impl/src/main/java/org/mule/runtime/module/deployment/impl/internal/maven/LightweightClassLoaderConfigurationBuilder.java
> +                    new LinkedList<>();
assign directly to the value of the collect below instead of using addAll

2023-04-05 14:25 UTC, elrodro83 commented on tests/runner/src/main/java/org/mule/test/runner/classification/DefaultWorkspaceReader.java
> +    if (isShadeMavenPlugin) {
`hasShadeMavenPlugin` ?

2023-04-05 14:25 UTC, elrodro83 commented on tests/runner/src/main/java/org/mule/test/runner/classification/DefaultWorkspaceReader.java
> +        throw new IllegalStateException(artifact + " has in its build configure the shadeMavenPlugin but default "
quote artifact in single quotes

2023-04-05 14:25 UTC, elrodro83 commented on tests/runner/src/main/java/org/mule/test/runner/classification/DefaultWorkspaceReader.java
> +        throw new IllegalStateException(artifact + " has in its build configure the shadeMavenPlugin but default "
`shadeMavenPlugin` -> `'maven-shade-plugin'`

2023-04-05 14:25 UTC, elrodro83 commented on tests/runner/src/main/java/org/mule/test/runner/classification/DefaultWorkspaceReader.java
> +        throw new IllegalStateException(artifact + " has in its build configure the shadeMavenPlugin but default "
`has in its build configure the` -> `has the PLUGIN configured in its build, `

2023-04-10 13:02 UTC, elrodro83 approved these changes

2023-04-10 15:44 UTC, jcgrethe commented
--validate

2023-04-10 17:38 UTC, jcgrethe commented
--validate

2023-04-10 20:28 UTC, merged