W-11855052: Database Connector to connect to SQL Anywhere via the sajdbc4 driver
mulesoft/mule pull request #12351
Opened 2023-03-31 12:59 UTC by alopezbizon

2023-03-31 13:27 UTC, IvanAndresFritzler requested changes

2023-03-31 13:27 UTC, IvanAndresFritzler commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/classloader/MuleApplicationClassLoader.java
> +  public static final String METHOD_NAME = "loadLibrary";
Move to line 43

2023-03-31 13:27 UTC, IvanAndresFritzler commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/classloader/MuleApplicationClassLoader.java
> +      loadNativeLibraries(name);
We can name this method as "loadNativeLibraryDependencies"

2023-03-31 13:27 UTC, IvanAndresFritzler commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/classloader/MuleApplicationClassLoader.java
> +  private void loadNativeLibraries(String nativeLibraryNameExcluded) {
Add a //TODO with the tickets that can improve this.

2023-03-31 13:27 UTC, IvanAndresFritzler commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/classloader/MuleApplicationClassLoader.java
> +        throw new MuleRuntimeException(e);
Improve this with an exception message.

2023-03-31 13:27 UTC, IvanAndresFritzler commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/nativelib/ArtifactCopyNativeLibraryFinder.java
> +import org.mule.runtime.api.exception.MuleRuntimeException;
Imports order.

2023-03-31 13:27 UTC, IvanAndresFritzler commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/nativelib/NativeLibraryFinder.java
> +  List<String> getNativeLibraries();
Add a TODO that will be deleted after the same tasks that we added to the ApplicationClassloader.

2023-03-31 13:27 UTC, IvanAndresFritzler commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/nativelib/NativeLibraryFinder.java
> +  List<String> getNativeLibraries();
Rename to findLibraryNames

2023-04-12 18:15 UTC, IvanAndresFritzler requested changes

2023-04-12 18:15 UTC, IvanAndresFritzler commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/nativelib/NativeExtension.java
> +  public String toString() {
Rename to value

2023-04-12 18:15 UTC, IvanAndresFritzler commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/nativelib/NativeExtension.java
> +public enum NativeExtension {
Rename to NativeLibraryFileExtension

2023-04-12 18:15 UTC, IvanAndresFritzler commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/nativelib/NativeLibraryFinder.java
> +  // TODO: W-12786373 Delete after do the same task added in the MuleApplicationClassloader.
// TODO: Delete after completing W-12786373

2023-04-12 18:27 UTC, alopezbizon commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/classloader/NativeLibraryLoaderMuleDeployableArtifactClassLoader.java
> +                                       createStaticMessage("Can not obtain the %s method to load the native library dependencies.",
The MuleRuntimeException only has 3 public constructors: `MuleRuntimeException(I18nMessage message)`, `MuleRuntimeException(I18nMessage message, Throwable cause)` and `MuleRuntimeException(Throwable cause)`. The constructor `MuleRuntimeException(String message, Throwable cause)` is private, so I can't use `String.format()`.

2023-04-12 19:02 UTC, alopezbizon commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/classloader/NativeLibraryLoaderMuleDeployableArtifactClassLoader.java
> +  protected void loadNativeLibraryDependencies(String nativeLibraryNameExcluded) {
Done.

2023-04-12 19:02 UTC, alopezbizon commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/nativelib/NativeExtension.java
> +  public String toString() {
Done.

2023-04-12 19:02 UTC, alopezbizon commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/nativelib/NativeLibraryFinder.java
> +  // TODO: W-12786373 Delete after do the same task added in the MuleApplicationClassloader.
Done.

2023-04-12 19:02 UTC, alopezbizon commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/nativelib/NativeExtension.java
> +public enum NativeExtension {
Done.

2023-04-12 20:35 UTC, alopezbizon commented
--validate

2023-04-13 14:45 UTC, alopezbizon commented
--validate

2023-04-13 19:52 UTC, alopezbizon commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/classloader/NativeLibraryLoaderMuleDeployableArtifactClassLoader.java
> +                                       createStaticMessage("Can not obtain the %s method to load the native library dependencies.",
Done.

2023-04-13 19:52 UTC, alopezbizon commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/classloader/NativeLibraryLoaderMuleDeployableArtifactClassLoader.java
> +          throw new MuleRuntimeException(
Done.

2023-04-13 20:39 UTC, IvanAndresFritzler approved these changes

2023-04-13 22:42 UTC, merged