W-12733611: Implement the tracing of the connection obtention
mulesoft/mule pull request #12391
Opened 2023-04-18 13:34 UTC by IvanAndresFritzler

2023-04-18 17:42 UTC, fsgonz requested changes

2023-04-18 17:42 UTC, fsgonz commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/internal/runtime/connectivity/ExtensionConnectionSupplier.java
>    @Inject
add a space.

2023-04-18 17:42 UTC, fsgonz commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/internal/runtime/connectivity/ExtensionConnectionSupplier.java
> +  public void setProfilingService(InternalProfilingService profilingService) {
Isn't it possible to inject the coreEventTracer directly?

2023-04-18 17:42 UTC, fsgonz commented on tests/infrastructure/src/main/java/org/mule/test/infrastructure/profiling/tracing/ExceptionEventMatcher.java
> +import org.hamcrest.Description;
import order.

2023-04-19 13:03 UTC, fsgonz requested changes

2023-04-19 13:03 UTC, fsgonz commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/internal/runtime/connectivity/ExtensionConnectionSupplier.java
> +  public static final String MULE_GET_CONNECTION = "mule:get-connection";
shouldn't this be a connection-create for the levels to take it accordingly?

2023-04-19 14:25 UTC, sofiamorseletto submitted a review, later dismissed

2023-04-19 20:16 UTC, fsgonz approved these changes

2023-04-20 14:06 UTC, IvanAndresFritzler commented
--validate

2023-04-20 14:29 UTC, sofiamorseletto approved these changes

2023-05-03 16:56 UTC, fsgonz approved these changes

2023-05-04 17:23 UTC, fsgonz approved these changes

2023-05-05 14:24 UTC, IvanAndresFritzler commented
--validate

2023-05-06 02:10 UTC, fsgonz commented
--validate

2023-05-09 12:41 UTC, merged