W-12586811: Add a log to indicate that the spans are exported when op…
mulesoft/mule pull request #12399
Opened 2023-04-20 15:28 UTC by alopezbizon

…tel spans export is enabled

2023-04-25 13:23 UTC, alopezbizon commented
--validate

2023-04-25 18:30 UTC, alopezbizon commented
--validate

2023-04-26 17:00 UTC, fsgonz requested changes
Add a log (in debug level for all the properties in OpentelemetryResources not only for batch size and exporter batch queue size. Basically log everything that is retrieved from the configuration layer.

2023-04-26 17:53 UTC, sofiamorseletto commented on modules/tracing/mule-tracer-exporter-impl/src/main/java/org/mule/runtime/tracer/exporter/impl/OpenTelemetrySpanExporterFactory.java
> +      LOGGER.info("{} is enabled.", MULE_OPEN_TELEMETRY_EXPORTER_ENABLED);
Maybe we could log a message instead of the name of the property for this case, like "Mule OpenTelemetry Exporter is enabled"

2023-04-26 18:12 UTC, fsgonz reviewed
Apart from Sofi's comment for the debug logging only add the endpoint and the protocol used.

2023-04-27 02:05 UTC, fsgonz approved these changes

2023-04-27 02:06 UTC, fsgonz commented
--validate

2023-04-28 13:07 UTC, merged