W-13065850: add automatic module for gateway dependencies
mulesoft/mule pull request #12406
Opened 2023-04-24 19:30 UTC by jcgrethe

2023-04-26 14:54 UTC, elrodro83 commented on modules/all-modules/pom.xml
> +        <javaModuleName>org.mule.runtime.all.modules</javaModuleName>
remove

2023-04-26 14:54 UTC, elrodro83 commented on modules/memory-management-parent/memory-management-tests/pom.xml
> +        <javaModuleName>org.mule.runtime.memory.management.tests</javaModuleName>
`org.mule.test.memory.management`

2023-04-26 14:54 UTC, elrodro83 commented on modules/memory-management-parent/pom.xml
> +        <javaModuleName>org.mule.runtime.memory.management.parent</javaModuleName>
remove

2023-04-26 14:54 UTC, elrodro83 commented on modules/reboot/pom.xml
> +        <javaModuleName>org.mule.runtime.reboot</javaModuleName>
`org.mule.boot`

2023-04-26 14:54 UTC, elrodro83 commented on tests/allure/pom.xml
> +		<javaModuleName>org.mule.runtime.test.allure</javaModuleName>
format

2023-04-26 14:54 UTC, elrodro83 commented on tests/component-plugin/pom.xml
> +        <javaModuleName>org.mule.runtime.test.component.plugin</javaModuleName>
`org.mule.test.component.plugin `

2023-04-26 14:54 UTC, elrodro83 commented on tests/pom.xml
> +        <javaModuleName>org.mule.runtime.mule.test.parent</javaModuleName>
remove

2023-04-26 14:56 UTC, elrodro83 commented on tests/test-extensions/classloading-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.classloading</javaModuleName>
`org.mule.test.extension.classloading `

2023-04-26 14:56 UTC, elrodro83 commented on tests/test-extensions/custom-object-store-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.custom.object.store</javaModuleName>
org.mule.test.extension.custom.object.store

2023-04-26 14:56 UTC, elrodro83 commented on tests/test-extensions/heisenberg-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.heisenberg</javaModuleName>
`org.mule.test.extension.heisenberg`

2023-04-26 14:56 UTC, elrodro83 commented on tests/test-extensions/implicit-config-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.implicit.config</javaModuleName>
`org.mule.test.extension.implicit.config `

2023-04-26 14:56 UTC, elrodro83 commented on tests/test-extensions/implicit-exclusive-config-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.implicit.exclusive.config</javaModuleName>
`org.mule.test.extension.implicit.exclusive.config `

2023-04-26 14:56 UTC, elrodro83 commented on tests/test-extensions/marvel-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.marvel</javaModuleName>
`org.mule.test.extension.marvel`

2023-04-26 14:56 UTC, elrodro83 commented on tests/test-extensions/metadata-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.metadata</javaModuleName>
`org.mule.test.extension.metadata`

2023-04-26 14:56 UTC, elrodro83 commented on tests/test-extensions/mule-soap-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.soap</javaModuleName>
`org.mule.test.extension.soap `

2023-04-26 14:56 UTC, elrodro83 commented on tests/test-extensions/multi-implicit-config-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.implicit.config</javaModuleName>
`org.mule.test.extension.implicit.config`

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/non-implicit-config-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.non.implicit.config</javaModuleName>
`org.mule.test.extension.non.implicit.config `

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/parameter-resolver-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.parameter.resolver</javaModuleName>
`org.mule.test.extension.parameter.resolver `

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/petstore-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.petstore</javaModuleName>
`org.mule.test.extension.petstore`

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extensions.parent</javaModuleName>
remove

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/reconnection-ext/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.reconnection</javaModuleName>
`org.mule.test.extension.reconnection`

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/resource-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.resource</javaModuleName>
`org.mule.test.extension.resource `

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/reusable-app/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.reusable.app</javaModuleName>
`org.mule.test.extension.reusable.app`

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/rick-and-morty-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.rick.and.morty</javaModuleName>
`org.mule.test.extension.rick.and.morty`

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/sample-data-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.sample.data</javaModuleName>
`org.mule.test.extension.sample.data `

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/semantic-terms-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.semantic.terms</javaModuleName>
`org.mule.test.extension.semantic.terms `

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/some-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.some</javaModuleName>
`org.mule.test.extension.some`

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/substitution-group-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.substitution.group</javaModuleName>
`org.mule.test.extension.substitution.group `

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/subtypes-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.subtype</javaModuleName>
`org.mule.test.extension.subtype`

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/test-config-properties-extension-deprecated-complex/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.config.properties.deprecated.complex</javaModuleName>
`org.mule.test.extension.config.properties.deprecated.complex`

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/test-config-properties-extension-deprecated/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.config.properties.deprecated</javaModuleName>
`org.mule.test.extension.config.properties.deprecated`

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/test-config-properties-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.config.properties</javaModuleName>
`org.mule.test.extension.config.properties `

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/test-crafted-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.crafted</javaModuleName>
`org.mule.test.extension.crafted `

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/test-localisation-properties-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.localisation</javaModuleName>
`org.mule.test.extension.localisation `

2023-04-26 14:59 UTC, elrodro83 commented on tests/test-extensions/test-oauth-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.oauth</javaModuleName>
`org.mule.test.extension.oauth`

2023-04-26 15:02 UTC, elrodro83 requested changes

2023-04-26 15:02 UTC, elrodro83 commented on tests/test-extensions/transactional-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.transactional</javaModuleName>
`org.mule.test.extension.transactional `

2023-04-26 15:02 UTC, elrodro83 commented on tests/test-extensions/typed-value-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.typed.value</javaModuleName>
`org.mule.test.extension.typed.value `

2023-04-26 15:02 UTC, elrodro83 commented on tests/test-extensions/values-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.values</javaModuleName>
`org.mule.test.extension.values `

2023-04-26 15:02 UTC, elrodro83 commented on tests/test-extensions/vegan-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.vegan</javaModuleName>
`org.mule.test.extension.vegan`

2023-04-26 15:02 UTC, elrodro83 commented on tests/test-extensions/weave-function-extension/pom.xml
> +        <javaModuleName>org.mule.runtime.test.extension.weave</javaModuleName>
`org.mule.test.extension.weave`

2023-04-26 15:02 UTC, elrodro83 commented on tests/test-plugins/dependant-plugin/pom.xml
> +        <javaModuleName>org.mule.runtime.test.plugin.dependant</javaModuleName>
`org.mule.test.plugin.dependant`

2023-04-26 15:02 UTC, elrodro83 commented on tests/test-plugins/pom.xml
> +        <javaModuleName>org.mule.runtime.test.plugins.parent</javaModuleName>
`org.mule.test.plugins.parent`

2023-04-26 15:02 UTC, elrodro83 commented on tests/test-policies/pom.xml
> +        <javaModuleName>org.mule.runtime.test.policies</javaModuleName>
`org.mule.test.policies `

2023-04-26 15:02 UTC, elrodro83 commented on tests/unit/pom.xml
> +        <javaModuleName>org.mule.runtime.test.unit</javaModuleName>
`org.mule.test.unit `

2023-04-26 16:46 UTC, elrodro83 commented on modules/tracing/pom.xml
> +        <javaModuleName>org.mule.runtime.tracing.parent</javaModuleName>
remove

2023-04-26 16:46 UTC, elrodro83 commented on tests/allure/pom.xml
> +		<formatterConfigPath>../../formatter.xml</formatterConfigPath>
format

2023-04-26 16:47 UTC, elrodro83 commented on tests/core-functional-tests/pom.xml
> +        <javaModuleName>org.mule.core.functional.tests</javaModuleName>
`org.mule.test.core.functional`

2023-04-26 16:55 UTC, elrodro83 approved these changes

2023-04-28 16:14 UTC, jcgrethe commented
--validate

2023-04-28 16:25 UTC, jcgrethe commented
--validate

2023-05-03 14:08 UTC, merged