W-13067198: Services packager: put service classes in a jar within the
mulesoft/mule pull request #12401
Opened 2023-04-21 13:54 UTC by elrodro83

service

2023-04-21 15:48 UTC, eze210 approved these changes

2023-04-24 14:52 UTC, rbourbonnavarro requested changes

2023-04-24 14:52 UTC, rbourbonnavarro commented on tests/runner/src/main/java/org/mule/test/runner/api/ServiceUrlClassification.java
> + * @since 4.0
4.0 -> 4.6

2023-04-24 15:06 UTC, elrodro83 commented on tests/runner/src/main/java/org/mule/test/runner/api/ServiceUrlClassification.java
> + * @since 4.0
```suggestion
 * @since 4.6
```

2023-04-24 20:20 UTC, rbourbonnavarro commented on tests/runner/src/main/java/org/mule/test/runner/api/ArtifactUrlClassification.java
> +   * @param artifact a {@link String} representing the name of the artifact. Not null.
Outdated jdoc.

2023-04-24 20:20 UTC, rbourbonnavarro commented on tests/runner/src/main/java/org/mule/test/runner/api/ArtifactUrlClassification.java
> +    requireNonNull(artifact, "name cannot be null");
Outdated message string.

2023-04-24 20:21 UTC, elrodro83 commented on tests/runner/src/main/java/org/mule/test/runner/api/ArtifactUrlClassification.java
> +    requireNonNull(artifact, "name cannot be null");
```suggestion
    requireNonNull(artifact, "artifact cannot be null");
```

2023-04-24 20:22 UTC, elrodro83 commented on tests/runner/src/main/java/org/mule/test/runner/api/ArtifactUrlClassification.java
> +   * @param artifact a {@link String} representing the name of the artifact. Not null.
```suggestion
   * @param artifactId a {@link String} representing the id of the artifact. Not null.
   * @param artifact the Maven artifact representation. Not null.
```

2023-04-24 20:23 UTC, elrodro83 commented on tests/runner/src/main/java/org/mule/test/runner/api/ArtifactUrlClassification.java
> +   * @param urls     list of {@link URL}s that would be used to create the {@link java.net.URLClassLoader}. Not null.
```suggestion
   * @param artifact   the Maven artifact representation. Not null.
   * @param urls       list of {@link URL}s that would be used to create the {@link java.net.URLClassLoader}. Not null.
```

2023-04-24 20:25 UTC, rbourbonnavarro approved these changes

2023-04-24 20:34 UTC, elrodro83 commented
--validate

2023-04-24 22:52 UTC, merged