W-12625688: Avoid errors caused by using mock/spy to ClassLoader
mulesoft/mule pull request #12416
Opened 2023-04-28 20:45 UTC by hyerans

2023-05-02 20:09 UTC, eze210 commented
--validate

2023-05-02 21:57 UTC, eze210 commented
There is a test (at least) that failed for me in spring-config module for the same reason (`LazyComponentInitializerAdapterTestCase`). Can you add the dependency there too?
I added it in another PR (#12420), but I think it makes more sense to add it here.

2023-05-02 23:27 UTC, hyerans commented
> There is a test (at least) that failed for me in spring-config module for the same reason (`LazyComponentInitializerAdapterTestCase`). Can you add the dependency there too? I added it in another PR (#12420), but I think it makes more sense to add it here.

Working on it now. Thanks Eze!

2023-05-03 16:56 UTC, hyerans commented
--validate

2023-05-03 18:56 UTC, elrodro83 requested changes

2023-05-03 18:56 UTC, elrodro83 commented on modules/extensions-support/pom.xml
> +            <version>4.11.0</version>
use the `${mockitoVersion}` property

2023-05-03 18:56 UTC, elrodro83 commented on modules/launcher/pom.xml
> +            <version>4.11.0</version>
use the `${mockitoVersion}` property

2023-05-05 14:48 UTC, elrodro83 approved these changes

2023-05-05 14:53 UTC, merged