W-13118963: Generate a module-info.java for mule bootstrap and logging
mulesoft/mule pull request #12412
Opened 2023-04-28 12:14 UTC by elrodro83

modules

2023-04-28 13:21 UTC, elrodro83 commented
--validate

2023-04-28 23:03 UTC, elrodro83 commented
--validate

2023-05-02 18:41 UTC, eze210 requested changes

2023-05-02 18:41 UTC, eze210 commented on modules/reboot/src/main/java/org/mule/runtime/module/reboot/api/MuleContainerBootstrapUtils.java
> +  // TODO remove
Missing ticket? Or missing in this PR?

2023-05-02 19:03 UTC, eze210 submitted a review, later dismissed

2023-05-02 20:29 UTC, elrodro83 commented
--validate

2023-05-03 14:13 UTC, elrodro83 commented
--validate

2023-05-03 15:18 UTC, eze210 approved these changes

2023-05-03 16:46 UTC, elrodro83 commented
--validate

2023-05-03 18:42 UTC, merged