W-13152861: Fix split internal packages in mule modules
mulesoft/mule pull request #12466
Opened 2023-05-16 18:20 UTC by mbuchwald

2023-05-16 19:20 UTC, rbourbonnavarro approved these changes

2023-05-16 19:27 UTC, rbourbonnavarro requested changes

2023-05-16 19:27 UTC, rbourbonnavarro commented on runtime-extension-model/src/main/java/org/mule/runtime/config/internal/dsl/processor/xml/provider/CoreXmlNamespaceInfoProvider.java
> +package org.mule.runtime.config.internal.dsl.processor.xml.provider;
This should change only in one of the modules, otherwise we end with the same split package issue.

2023-05-16 19:45 UTC, rbourbonnavarro approved these changes

2023-05-17 12:16 UTC, mbuchwald commented
--validate

2023-05-17 14:53 UTC, merged