W-13065369: User Story B - Integration of Optel metrics exporter and …
mulesoft/mule pull request #12496
Opened 2023-05-29 15:12 UTC by fsgonz

…mule runtime tracer for AllStatistics metrics

2023-06-08 17:44 UTC, fsgonz commented
--validate

2023-06-13 17:43 UTC, fsgonz commented
--validate

2023-06-26 12:59 UTC, fsgonz commented
--validate

2023-06-26 14:54 UTC, fsgonz commented
--validate

2023-06-26 19:58 UTC, IvanAndresFritzler requested changes

2023-06-26 19:58 UTC, IvanAndresFritzler commented on modules/metrics/mule-metrics-exporter-impl/src/main/java/org/mule/runtime/metrics/exporter/impl/OpenTelemetryMeterExporter.java
> +import io.opentelemetry.api.metrics.LongCounterBuilder;
Import order (review all imports since there more than one that needs re arrange)

2023-06-26 19:58 UTC, IvanAndresFritzler commented on modules/metrics/mule-metrics-exporter-impl/src/main/java/org/mule/runtime/metrics/exporter/impl/OpentelemetryExporterAttributes.java
> +import io.opentelemetry.api.common.AttributeKey;
Import order

2023-06-26 19:58 UTC, IvanAndresFritzler commented on modules/metrics/mule-metrics-impl/src/test/java/org/mule/runtime/metrics/impl/instrument/DefaultLongCounterTestCase.java
> +import java.util.concurrent.atomic.AtomicLong;
Import order

2023-06-26 19:58 UTC, IvanAndresFritzler commented on modules/metrics/mule-metrics-impl/src/test/java/org/mule/runtime/metrics/impl/instrument/DefaultLongUpDownCounterTestCase.java
> +import static org.mockito.Mockito.when;
Import order

2023-06-26 20:43 UTC, fsgonz commented
--validate

2023-06-27 20:27 UTC, IvanAndresFritzler approved these changes

2023-06-27 20:29 UTC, merged