W-13588449: Parse template target value breaking change.
mulesoft/mule pull request #12704
Opened 2023-08-15 18:49 UTC by IvanAndresFritzler

2023-08-16 19:23 UTC, IvanAndresFritzler commented
--validate

2023-08-16 20:30 UTC, elrodro83 submitted a review, later dismissed

2023-08-22 13:53 UTC, fsgonz requested changes

2023-08-22 13:53 UTC, fsgonz commented on modules/core-components/src/test/java/org/mule/runtime/core/internal/processor/simple/ParseTemplateProcessorTestCase.java
> +        new SystemProperty(MuleSystemProperties.PARSE_TEMPLATE_USE_LEGACY_DEFAULT_TARGET_VALUE, isUseLegacyDefaultTargetValue);
static import.

2023-08-22 14:24 UTC, fsgonz approved these changes

2023-08-22 16:50 UTC, IvanAndresFritzler commented
--validate

2023-08-23 12:47 UTC, IvanAndresFritzler commented
--validate

2023-08-23 14:59 UTC, merged