W-13994259: Single thread subscription of flow related Fluxes causes StackOverflow errors.
mulesoft/mule pull request #12806
Opened 2023-09-15 17:45 UTC by IvanAndresFritzler

2023-09-15 18:01 UTC, fsgonz requested changes

2023-09-15 18:01 UTC, fsgonz commented on core/src/main/java/org/mule/runtime/core/internal/util/rx/RxUtils.java
> +        if (!subscribed) {
Can we add a logger with a warning a case extra calls happen, because a far as I understand it would be an unexpected behavior.

2023-09-15 20:49 UTC, fsgonz commented on core/src/main/java/org/mule/runtime/core/internal/util/rx/RxUtils.java
> +  public static class MultiFluxSubscriber<T> implements CoreSubscriber<T> {
Ok, this will be refactor later. It's clear for now as we talked.

2023-09-15 20:49 UTC, fsgonz commented on core/src/main/java/org/mule/runtime/core/internal/util/rx/RxUtils.java
> +        if (!subscribed) {
possible internal reactor behavior as discussed.

2023-09-15 20:49 UTC, fsgonz submitted a review, later dismissed

2024-03-12 18:52 UTC, IvanAndresFritzler commented
--validate

2025-06-25 21:49 UTC, closed without merging