W-14145356: Modularize core-components
mulesoft/mule pull request #12878
Opened 2023-10-03 14:32 UTC by mbuchwald

2023-10-03 14:44 UTC, mbuchwald commented
--validate

2023-10-03 15:02 UTC, mbuchwald commented
--validate

2023-10-03 16:01 UTC, elrodro83 requested changes

2023-10-03 16:01 UTC, elrodro83 commented on modules/core-components/pom.xml
> +            <groupId>net.bytebuddy</groupId>
isn't this transitive form mockito-inline?

2023-10-03 16:01 UTC, elrodro83 commented on modules/core-components/src/main/java/module-info.java
> +  requires java.desktop;
what is used form this/who uses this?

2023-10-03 18:31 UTC, elrodro83 approved these changes

2023-10-03 19:30 UTC, mbuchwald commented
--validate

2023-10-03 20:40 UTC, mbuchwald commented
--validate

2023-10-04 12:55 UTC, mbuchwald commented
--validate

2023-10-04 15:26 UTC, mbuchwald commented
--validate

2023-10-04 17:50 UTC, mbuchwald commented
--validate

2023-10-04 18:45 UTC, mbuchwald commented
--validate

2023-10-04 19:30 UTC, elrodro83 approved these changes

2023-10-05 04:01 UTC, merged