W-13829786: Avoid reading mule-module.properties for modules with module-info
mulesoft/mule pull request #12901
Opened 2023-10-10 18:48 UTC by elrodro83

2023-10-10 19:19 UTC, asanguinetti requested changes

2023-10-10 19:19 UTC, asanguinetti commented on modules/container/src/main/java/org/mule/runtime/container/internal/ContainerModulesDiscovererProvider.java
> +public class ContainerModulesDiscovererProvider {
JDoc

2023-10-10 19:19 UTC, asanguinetti commented on modules/container/src/main/java11/org/mule/runtime/container/internal/ContainerModulesDiscovererProvider.java
> +public class ContainerModulesDiscovererProvider {
JDoc

2023-10-10 19:19 UTC, asanguinetti commented on tests/infrastructure/src/main/java/org/mule/test/infrastructure/deployment/AbstractFakeMuleServerTestCase.java
> +      new SystemProperty(CLASSLOADER_CONTAINER_JPMS_MODULE_LAYER, "false");
Why is it that we are enforcing this for these tests? Could you elaborate?

2023-10-11 17:24 UTC, asanguinetti approved these changes

2023-10-11 19:40 UTC, elrodro83 commented
--validate

2023-10-12 19:57 UTC, merged