W-12356140: [SingleApp] Avoid on-demand artifact deployment
mulesoft/mule pull request #13010
Opened 2023-11-17 17:51 UTC by alopezbizon

2023-11-17 19:23 UTC, alopezbizon commented
--validate

2023-11-21 13:05 UTC, fsgonz commented on modules/deployment/src/main/java/org/mule/runtime/module/deployment/internal/ManagerDeploymentDirectoryWatcher.java
> +public class ManagerDeploymentDirectoryWatcher {
This should be named as a provider or something like that. This is not a watcher but obtains the watcher.

2023-11-30 14:19 UTC, alopezbizon commented
--validate

2023-12-04 12:30 UTC, fsgonz commented on modules/deployment/src/main/java/org/mule/runtime/module/deployment/internal/DeploymentExecutor.java
> +import static java.lang.System.getProperties;
static import order.

2023-12-04 12:31 UTC, fsgonz commented on modules/deployment/src/main/java/org/mule/runtime/module/deployment/internal/DeploymentExecutor.java
> +    if (!isSingleDeployment() || (isSingleDeployment() && !this.artifactDeployed)) {
try to create a polymorphism where this "if" is taken into account. An interface and two classes and create the deployment service accordingly in the mule container as talked.

2023-12-04 12:31 UTC, fsgonz commented on modules/deployment/src/main/java/org/mule/runtime/module/deployment/internal/DeploymentExecutor.java
> +  public <D extends DeployableArtifactDescriptor, T extends Artifact<D>> void deploy(final URI artifactArchiveUri,
jdoc.

2023-12-04 12:32 UTC, fsgonz commented on modules/deployment/src/main/java/org/mule/runtime/module/deployment/internal/DeploymentExecutor.java
> +    return getProperties().containsKey(SINGLE_DEPLOYMENT_PROPERTY);
Evaluate this once and not every time you invoke the method. The sysprops will not vary.

2023-12-04 12:33 UTC, fsgonz commented on modules/deployment/src/main/java/org/mule/runtime/module/deployment/internal/DeploymentExecutor.java
> +      this.artifactDeployed = true;
verify that this is set as deployed after you know that you really deployed the artifact, not when you attempt to deploy it.

2023-12-06 13:03 UTC, fsgonz requested changes

2023-12-18 17:47 UTC, fsgonz approved these changes

2023-12-20 13:30 UTC, alopezbizon commented
--validate

2023-12-20 17:12 UTC, merged