W-14338813: Move transactionManager lifecycle/ioc tests to unit tests
mulesoft/mule pull request #13096
Opened 2023-12-14 20:46 UTC by mbuchwald

2023-12-14 21:59 UTC, mbuchwald commented
--validate

2023-12-15 13:21 UTC, mbuchwald commented
--validate

2023-12-15 13:50 UTC, eze210 requested changes

2023-12-15 13:50 UTC, eze210 commented on modules/core-components/src/test/java/org/mule/runtime/core/internal/processor/XaNestedTransactionsTestCase.java
> +public class XaNestedTransactionsTestCase extends AbstractMuleContextTestCase {
Add the allure annotations

2023-12-15 15:21 UTC, eze210 approved these changes

2023-12-15 17:01 UTC, merged