W-12356145: [SingleApp] Exit MuleRuntime on app deployment failure
mulesoft/mule pull request #13113
Opened 2023-12-22 15:56 UTC by fsgonz

2023-12-26 20:10 UTC, fsgonz commented
--validate

2023-12-26 20:45 UTC, fsgonz commented
--validate

2023-12-27 14:22 UTC, IvanAndresFritzler requested changes

2023-12-27 14:22 UTC, IvanAndresFritzler commented on modules/deployment/src/main/java/org/mule/runtime/module/deployment/api/DeploymentService.java
> +  default void onFatalErrorForContainer(Consumer<Throwable> onFatalErrorForContainerConsumer) {
Naming: onDeploymentError

2023-12-27 14:37 UTC, IvanAndresFritzler approved these changes

2023-12-27 17:10 UTC, merged