W-14608096: timeout is not being considered for local transactions
mulesoft/mule pull request #13157
Opened 2024-01-09 19:30 UTC by mbuchwald

This can also involve XA Transactions, when there is no error but timeout has been reached, the tx should be rolled back and an error has to be thrown so the execution doesn't continue as if nothing happened (and also allows for error handling for TryScope scenarios).

2024-01-10 17:55 UTC, elrodro83 requested changes

2024-01-10 17:55 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/context/DefaultMuleContext.java
> +    featureFlaggingRegistry.registerFeatureFlag(ERROR_AND_ROLLBACK_TX_WHEN_TIMEOUT, minMuleVersion("4.6.0"));
4.6.1?

2024-01-10 17:55 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/exception/OnErrorPropagateHandler.java
> +        logger.error("Cannot rollback current transaction", e);
why are you not adding this as suppressed in this case?

2024-01-10 17:55 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/transaction/DelegateTransaction.java
> +    this.timeout = timeout;
use super.setTimeout instead of accessing the filed directly

2024-01-10 17:55 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/privileged/transaction/AbstractTransaction.java
> +      if (rollbackAfterTimeout && timeoutReached()) {
what if at the time of calling `rollback` it was within time, but at this call the timeout has passed?

2024-01-10 17:55 UTC, elrodro83 commented on modules/core-components/src/test/java/org/mule/runtime/core/internal/processor/TransactionalTryTimeoutTestCase.java
> +public class TransactionalTryTimeoutTestCase extends AbstractMuleContextTestCase {
allure

2024-01-10 20:08 UTC, elrodro83 requested changes

2024-01-10 20:08 UTC, elrodro83 commented on runtime-extension-model/src/main/java/org/mule/runtime/core/api/error/Errors.java
> +import static org.mule.runtime.core.api.error.Errors.Identifiers.*;
do not use * imports

2024-01-10 20:17 UTC, mbuchwald commented on core/src/main/java/org/mule/runtime/core/internal/exception/OnErrorPropagateHandler.java
> +      Throwable cause = e.getCause();
The thrown error would be the TransactionException, which is wrapping the actual cause (in our case, the timeout)

2024-01-11 12:07 UTC, elrodro83 submitted a review, later dismissed

2024-01-11 16:45 UTC, mbuchwald commented
--validate

2024-01-11 17:19 UTC, mbuchwald commented
--validate

2024-01-11 19:22 UTC, mbuchwald commented
--validate

2024-01-11 21:37 UTC, mbuchwald commented
--validate

2024-01-12 13:38 UTC, elrodro83 approved these changes

2024-01-12 13:39 UTC, merged