W-14610032: extract `RetryPolicyTemplate` and associates from `mule-core`
mulesoft/mule pull request #13178
Opened 2024-01-15 20:58 UTC by rbourbonnavarro

2024-01-16 14:56 UTC, elrodro83 requested changes

2024-01-16 14:56 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/api/retry/RetryCallback.java
> +@Deprecated
add the javadoc indicating the replacement

2024-01-16 14:56 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/api/retry/RetryContext.java
> +@Deprecated
indicate the replacement in the javadoc

2024-01-16 14:56 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/api/retry/RetryNotifier.java
> +@Deprecated
indicate the replacement in the javadoc

2024-01-16 14:56 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/api/retry/policy/PolicyStatus.java
> +public final class PolicyStatus implements org.mule.runtime.retry.api.policy.PolicyStatus {
deprecate?

2024-01-16 14:56 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/api/retry/policy/RetryPolicy.java
> +@Deprecated
indicate the replacement in the javadoc

2024-01-16 14:56 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/api/retry/policy/RetryPolicyTemplate.java
> +public interface RetryPolicyTemplate extends org.mule.runtime.retry.api.policy.RetryPolicyTemplate {
deprecate?

2024-01-16 14:56 UTC, elrodro83 commented on mule-retry-api/api-changes.json
> +          "classQualifiedName": "org.reactivestreams.Publisher",
mule-api does not have this dependency

2024-01-16 14:56 UTC, elrodro83 commented on mule-retry-api/api-changes.json
> +          "classQualifiedName": "org.reactivestreams.Subscriber",
mule-api does not have this dependency

2024-01-16 14:56 UTC, elrodro83 commented on mule-retry-api/api-changes.json
> +          "classQualifiedName": "org.reactivestreams.Subscription",
mule-api does not have this dependency

2024-01-16 14:56 UTC, elrodro83 commented on mule-retry-api/src/main/java/org/mule/runtime/retry/api/policy/RetryPolicy.java
> +  default <T> Publisher<T> applyPolicy(Publisher<T> publisher,
this method uses reactivestreams, it should not be part of the api. Isn't this used only by the container?

2024-01-16 14:56 UTC, elrodro83 commented on mule-retry-api/src/main/java/org/mule/runtime/retry/api/policy/RetryPolicy.java
> +  default <T> Publisher<T> applyPolicy(Publisher<T> publisher,
this method uses reactivestreams, it should not be part of the api. Isn't this used only by the container?

2024-01-16 14:56 UTC, elrodro83 commented on mule-retry-api/src/main/java/org/mule/runtime/retry/api/policy/RetryPolicyTemplate.java
> +  default <T> Publisher<T> applyPolicy(Publisher<T> publisher) {
this method uses reactivestreams, it should not be part of the api. Isn't this used only by the container?

2024-01-16 14:56 UTC, elrodro83 commented on mule-retry-api/src/main/java/org/mule/runtime/retry/api/policy/RetryPolicyTemplate.java
> +  default <T> Publisher<T> applyPolicy(Publisher<T> publisher, Scheduler retryScheduler) {
this method uses reactivestreams, it should not be part of the api. Isn't this used only by the container?

2024-01-16 14:56 UTC, elrodro83 commented on mule-retry-api/src/main/java/org/mule/runtime/retry/api/policy/RetryPolicyTemplate.java
> +  default <T> Publisher<T> applyPolicy(Publisher<T> publisher,
this method uses reactivestreams, it should not be part of the api. Isn't this used only by the container?

2024-01-16 14:56 UTC, elrodro83 commented on mule-retry-api/src/main/java/org/mule/runtime/retry/api/policy/util/rx/RxUtils.java
> +public class RxUtils {
do you really need this here?

2024-02-15 16:43 UTC, rbourbonnavarro commented
--validate

2024-02-16 20:35 UTC, asanguinetti approved these changes

2024-02-19 20:47 UTC, merged