W-15284273: Extract artifact versions in poms for artifact-activation tests
mulesoft/mule pull request #13526
Opened 2024-05-28 18:36 UTC by elrodro83

2024-05-28 18:44 UTC, rbourbonnavarro requested changes

2024-05-28 18:44 UTC, rbourbonnavarro commented on pom.xml
> +        <mule.maven.plugin.version>3.7.0-SNAPSHOT</mule.maven.plugin.version>
We could use latest `4.1.1` here (btw, applications are never packaged)

2024-05-29 12:32 UTC, rbourbonnavarro commented on modules/artifact-activation/src/test/java/org/mule/runtime/module/artifact/activation/internal/deployable/MavenDeployableProjectModelBuilderTestCase.java
> +               hasItems(hasProperty("descriptor", hasProperty("artifactId", equalTo("mule-db-connector")))));
What is the other item?

2024-05-29 12:36 UTC, rbourbonnavarro submitted a review, later dismissed

2024-05-29 12:40 UTC, rbourbonnavarro approved these changes

2024-05-29 14:05 UTC, elrodro83 commented
--validate

2024-05-30 14:54 UTC, rbourbonnavarro approved these changes

2024-05-30 14:54 UTC, merged