W-15894519: Deleting an App with DLL on Windows can cause a memory leak
mulesoft/mule pull request #13580
Opened 2024-06-24 21:57 UTC by alopezbizon

2024-06-25 14:21 UTC, IvanAndresFritzler requested changes

2024-06-25 14:21 UTC, IvanAndresFritzler commented on modules/deployment/src/main/java/org/mule/runtime/module/deployment/internal/NativeLibrariesFileDeletion.java
> +    File appNativeLibrariesTempFolder = getAppNativeLibrariesTempFolder(applicationName);
We cannot delete all libs like this. Either we have a folder for this deployment in particular or we know the file names of the libraries that we must delete. Consider that the same app can be re-deployed in the meantime. Try looking at DeployableArtifactDescriptor and the MuleApplicationClassLoaderFactory (maybe we can add a native libs folder name at the descriptor and use it at the factory to create the NativeLibraryFinderFactory).

2024-06-25 14:21 UTC, IvanAndresFritzler commented on modules/deployment/src/main/java/org/mule/runtime/module/deployment/internal/RetryScheduledFileDeletionTask.java
> +        scheduler.shutdown();
Log that we failed to delete and no retries will be made.

2024-06-26 16:58 UTC, alopezbizon commented
--validate

2024-06-26 20:26 UTC, IvanAndresFritzler requested changes

2024-06-26 20:26 UTC, IvanAndresFritzler commented on modules/artifact/src/main/java/org/mule/runtime/module/artifact/api/descriptor/DeployableArtifactDescriptor.java
> +  public String getIdentifier() {
Lets put getLoadedNativeLibrariesFolderName()

2024-06-26 20:26 UTC, IvanAndresFritzler commented on modules/artifact/src/main/java/org/mule/runtime/module/artifact/api/descriptor/DeployableArtifactDescriptor.java
> +  private final String identifier = valueOf(currentTimeMillis());
Lets use an UUID to avoid collisions if (for any reason) the folders do no get deleted.

2024-06-26 20:26 UTC, IvanAndresFritzler commented on modules/artifact-activation/src/main/java/org/mule/runtime/module/artifact/activation/internal/nativelib/NativeLibraryFinderFactory.java
> +   * @param identifier of the artifact
Adjust (I think this should say it's the name of the folder)

2024-06-26 20:26 UTC, IvanAndresFritzler commented on modules/deployment/src/main/java/org/mule/runtime/module/deployment/internal/RetryScheduledFileDeletionTask.java
> +        message = "Failed to perform the action. No further retries will be made.";
This one should be error log

2024-06-26 20:26 UTC, IvanAndresFritzler commented on modules/deployment/src/main/java/org/mule/runtime/module/deployment/internal/RetryScheduledFileDeletionTask.java
> +        message = format("Attempt %s. Failed to perform the action. Retrying...", attempt);
This one should be warning log

2024-06-26 20:26 UTC, IvanAndresFritzler commented on modules/deployment/src/main/java/org/mule/runtime/module/deployment/internal/NativeLibrariesFileDeletion.java
> +    } catch (IOException e) {
Either you catch Throwable here or you need to add a catch for the rest of the possible exceptions at the RetryScheduledFileDeletionTask#performAction to trap all the rest of them.
We should unit test this too.

2024-07-01 20:33 UTC, IvanAndresFritzler requested changes

2024-07-01 20:33 UTC, IvanAndresFritzler commented on modules/deployment/src/main/java/org/mule/runtime/module/deployment/internal/DefaultArchiveDeployer.java
> +        final String appName = artifact.getDescriptor().getDataFolderName();
This is not the appName but the change is not even necessary so you can restore the original line.

final File dataFolder = getAppDataFolder(artifact.getDescriptor().getDataFolderName());

2024-07-01 20:33 UTC, IvanAndresFritzler commented on modules/deployment/src/test/java/org/mule/runtime/module/deployment/test/internal/NativeLibrariesFolderDeletionTestCase.java
> +  private static class TestNeverNativeLibrariesFileDeletion extends NativeLibrariesFolderDeletion {
You can use a mock instead of a stub here.

2024-07-01 20:33 UTC, IvanAndresFritzler commented on modules/deployment/src/test/java/org/mule/runtime/module/deployment/test/internal/NativeLibrariesFolderDeletionTestCase.java
> +  private static class TestAtSecondAttemptNativeLibrariesFileDeletion extends NativeLibrariesFolderDeletion {
Mock too.

2024-07-11 15:29 UTC, IvanAndresFritzler approved these changes

2024-07-11 17:16 UTC, alopezbizon commented
--validate

2024-07-11 21:40 UTC, merged