W-16188357: Mule Runtime is unable to find properties files at /lib/user
mulesoft/mule pull request #13677
Opened 2024-07-26 19:16 UTC by marianorean

2024-07-29 16:41 UTC, elrodro83 requested changes

2024-07-29 16:41 UTC, elrodro83 commented on modules/boot-api/src/test/java/org/mule/runtime/module/boot/internal/DefaultMuleClassPathConfigTestCase.java
> +                                     new URLClassLoader(muleClassPathConfig.getResourceURLs()
this is replicating the actual behaviour, instead of testing the productive code. If the productive code is broken, this test will still pass

2024-07-29 17:12 UTC, elrodro83 approved these changes

2024-07-31 13:27 UTC, marianorean commented
--validate

2024-07-31 17:15 UTC, marianorean commented
--validate

2024-07-31 20:45 UTC, marianorean commented
--validate

2024-08-02 13:28 UTC, merged