W-16676258: Use WatchService for TracingConfigurationFileWatcher
mulesoft/mule pull request #13826
Opened 2024-09-05 19:10 UTC by lbarrios

2024-09-05 19:20 UTC, fsgonz requested changes

2024-09-05 19:20 UTC, fsgonz commented on modules/tracing/mule-tracer-common/src/main/java/org/mule/runtime/tracer/common/watcher/TracingConfigurationFileWatcher.java
> +import static java.nio.file.StandardWatchEventKinds.ENTRY_DELETE;
order of static imports.
Usually we follow this convention:
static imports
       -> mule -> java -> other ones
import
       -> mule classes -> java -> other ones.

2024-09-05 19:48 UTC, fsgonz submitted a review, later dismissed

2024-09-05 19:57 UTC, fsgonz submitted a review, later dismissed

2024-09-10 17:22 UTC, fsgonz approved these changes

2024-09-13 17:38 UTC, fsgonz commented
--validate

2024-09-20 13:44 UTC, lbarrios commented
--validate

2025-06-25 21:50 UTC, closed without merging