W-15838197: Remove APIs from mule exposing removed java ee classes/interfaces
mulesoft/mule pull request #13891
Opened 2024-09-27 13:43 UTC by marianorean

2024-09-27 17:59 UTC, marianorean commented
--validate

2024-10-04 11:38 UTC, marianorean commented
--validate

2024-10-04 15:44 UTC, elrodro83 requested changes
Move remaining privileged documentation stuff to api

2024-10-04 15:44 UTC, elrodro83 commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/privileged/resources/documentation/ExtensionDescriptionsSerializer.java
> +public abstract class ExtensionDescriptionsSerializer {
make an interface

2024-10-04 15:44 UTC, elrodro83 commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/privileged/resources/documentation/XmlExtensionDocumentation.java
> +public abstract class XmlExtensionDocumentation {
make an interface

2024-10-04 15:44 UTC, elrodro83 commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/privileged/resources/documentation/XmlExtensionElementDocumentation.java
> +public abstract class XmlExtensionElementDocumentation {
make an interface

2024-10-04 15:44 UTC, elrodro83 commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/privileged/resources/documentation/XmlExtensionParameterDocumentation.java
> +public abstract class XmlExtensionParameterDocumentation {
make an interface

2024-10-04 17:13 UTC, elrodro83 requested changes

2024-10-04 17:13 UTC, elrodro83 commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/api/resources/documentation/ExtensionDescriptionsSerializer.java
> +public interface ExtensionDescriptionsSerializer {
add javadocs

2024-10-04 17:13 UTC, elrodro83 commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/api/resources/documentation/XmlExtensionElementDocumentation.java
> +public interface XmlExtensionElementDocumentation {
javadoc

2024-10-04 17:13 UTC, elrodro83 commented on modules/extensions-support/src/main/java/module-info.java
> -        "org.mule.runtime.module.extension.privileged.resources.documentation"
add the export for the new package, keep the comment mentioning who is using it

2024-10-04 17:28 UTC, elrodro83 approved these changes

2024-10-04 17:37 UTC, marianorean commented
--validate

2024-10-04 19:07 UTC, marianorean commented
--validate

2024-10-04 19:48 UTC, marianorean commented
--validate

2024-10-04 23:00 UTC, merged