W-16814280: fix plugin class loader leak
mulesoft/mule pull request #13926
Opened 2024-10-21 13:41 UTC by rbourbonnavarro

2024-10-21 14:54 UTC, rbourbonnavarro commented
--validate

2024-10-22 13:32 UTC, rbourbonnavarro commented
--validate

2024-10-22 15:09 UTC, elrodro83 requested changes

2024-10-22 15:09 UTC, elrodro83 commented on modules/deployment/src/test/java/org/mule/runtime/module/deployment/test/internal/XmlPluginClassLoaderLeakOnDeploymentTestCase.java
> +      () -> new HashSet<>(singletonList(byeXmlExtensionPlugin));
just `singleton()`?

2024-10-22 15:09 UTC, elrodro83 commented on modules/extensions-xml-support/src/main/java/org/mule/runtime/extension/internal/loader/xml/XmlExtensionLoaderDelegate.java
> +  public static void forceTransformerPoolRecreation(boolean force) {
add as depecated

2024-10-22 16:29 UTC, elrodro83 approved these changes

2024-10-22 19:06 UTC, merged