MULE-18717: Cache MetadataType when declaring an Extension as part of…
mulesoft/mule pull request #9333
Opened 2020-09-01 15:07 UTC by gsfernandes

… ExtensionModelLoader process

2020-09-02 07:05 UTC, lucianoRM requested changes

2020-09-02 07:05 UTC, lucianoRM commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/internal/loader/java/type/runtime/ExtensionTypeWrapper.java
> +      Objects.requireNonNull(classTypeLoader, "classTypeLoader cannot be null");
static import

2020-09-02 19:03 UTC, gsfernandes commented
@estebanwasinger @marianogonzalez please review this change. I found this while profiling response times for design services operations. The solution that will speed up a lot this process is the initiative for "base extension model" but this at least helps us to improve a bit the performance while avoiding loading over and over same MetadataTypes.

2020-09-02 20:14 UTC, estebanwasinger submitted a review, later dismissed

2020-09-02 20:26 UTC, marianogonzalez requested changes

2020-09-02 20:26 UTC, marianogonzalez commented on modules/extensions-support/src/main/java/org/mule/runtime/module/extension/internal/loader/java/type/runtime/ExtensionTypeWrapper.java
> +    private Map<Type, MetadataType> typeMetadataTypeMap = new HashMap<>();
use a weakhashmap

2020-09-02 21:34 UTC, marianogonzalez approved these changes

2020-09-03 11:20 UTC, lucianoRM approved these changes

2020-09-03 11:32 UTC, merged