MULE-18788: Remove visitable components to resolve stats decoration
mulesoft/mule pull request #9450
Opened 2020-09-23 02:24 UTC by fsgonz

2020-09-23 03:09 UTC, fsgonz commented
--validate

2020-09-23 12:10 UTC, elrodro83 requested changes

2020-09-23 12:10 UTC, elrodro83 commented on core/src/main/java/org/mule/runtime/core/internal/util/message/MessageUtils.java
>     * @param eventCorrelationId the correlationId of the context involed
involved

2020-09-23 14:40 UTC, fsgonz commented
--validate

2020-09-23 15:40 UTC, elrodro83 approved these changes

2020-09-23 17:33 UTC, fsgonz commented
--validate

2020-09-23 20:04 UTC, fsgonz commented
--validate

2020-09-24 12:44 UTC, fsgonz commented
--validate

2020-09-24 16:14 UTC, fsgonz commented
--validate

2020-09-24 22:58 UTC, merged