MULE-18805: onError Nesteable Component model fail in lazy initialisation
mulesoft/mule pull request #9524
Opened 2020-10-08 14:01 UTC by mbuchwald

2020-10-08 17:54 UTC, mbuchwald commented
--validate

2020-10-08 18:35 UTC, elrodro83 requested changes

2020-10-08 18:35 UTC, elrodro83 commented on modules/spring-config/src/main/java/org/mule/runtime/config/internal/model/ComponentModel.java
> +import static org.mule.runtime.internal.dsl.DslConstants.*;
no `*`

2020-10-08 19:19 UTC, elrodro83 approved these changes

2020-10-13 12:19 UTC, mbuchwald commented
--verify

2020-10-13 16:43 UTC, mbuchwald commented
--validate

2020-10-14 13:16 UTC, mbuchwald commented
--validate

2020-10-15 16:58 UTC, mbuchwald commented
--validate

2020-10-15 17:37 UTC, mbuchwald commented
--validate

2020-10-15 18:01 UTC, elrodro83 approved these changes

2020-10-15 18:29 UTC, mbuchwald commented
--validate

2020-10-15 20:07 UTC, merged