MULE-18871: Fix flaky test org.mule.test.module.extension.source.HeisenbergMessageSourceTestCase.sourceRestartedWithDynamicConfig
mulesoft/mule pull request #9532
Opened 2020-10-08 21:02 UTC by pabloperalta

…enbergMessageSourceTestCase.sourceRestartedWithDynamicConfig

2020-10-13 13:01 UTC, pabloperalta commented
--validate

2020-10-13 16:48 UTC, eze210 commented
--validate

2020-10-13 16:49 UTC, eze210 requested changes

2020-10-13 16:49 UTC, eze210 commented on modules/extensions-spring-support/src/test/java/org/mule/test/module/extension/source/HeisenbergMessageSourceTestCase.java
> +            assertThat("The flow did not stop in a reasonable amount of time", flow.getLifecycleState().isStopped(), is(true));
return flow.getLifecycleState().isStopped();

2020-10-13 16:49 UTC, eze210 commented on modules/extensions-spring-support/src/test/java/org/mule/test/module/extension/source/HeisenbergMessageSourceTestCase.java
> +            assertThat("The flow did not stop in a reasonable amount of time", flow.getLifecycleState().isStopped(), is(true));
And move the error message to the probe description

2020-10-13 19:41 UTC, eze210 approved these changes

2020-10-15 12:07 UTC, pabloperalta commented
--validate

2020-10-15 17:42 UTC, pabloperalta commented
--validate

2020-10-19 12:34 UTC, pabloperalta commented
--validate

2020-10-20 14:43 UTC, pabloperalta commented
--validate

2020-10-20 21:21 UTC, merged