remove returns
mulesoft/mule pull request #9555
Opened 2020-10-14 15:35 UTC by elrodro83

2020-10-14 17:47 UTC, elrodro83 commented
--validate

2020-10-15 14:23 UTC, elrodro83 commented
--validate

2020-10-15 17:18 UTC, elrodro83 commented
--validate

2020-10-15 17:53 UTC, elrodro83 commented
--validate

2020-10-15 18:30 UTC, elrodro83 commented
--validate

2020-10-15 22:47 UTC, elrodro83 commented
--validate

2020-10-16 15:27 UTC, elrodro83 commented
--validate

2020-10-16 15:35 UTC, fsgonz requested changes

2020-10-16 15:35 UTC, fsgonz commented on core-tests/src/test/java/org/mule/runtime/core/internal/management/stats/PayloadStatisticsTestCase.java
> +  @Description("Check that decorated cursors also are cursors so the fucntionality depending on instanceof is not affected.")
functionality

2020-10-16 15:36 UTC, fsgonz commented on core-tests/src/test/java/org/mule/runtime/core/internal/management/stats/PayloadStatisticsTestCase.java
> +  @Description("Check that decorated cursors also are cursors so the fucntionality depending on instanceof is not affected.")
so that

2020-10-16 16:33 UTC, fsgonz approved these changes

2020-10-16 18:35 UTC, merged