EE-7505: Remove sysProp `mule.schedulers.latency.report.interval` and…
mulesoft/mule pull request #9652
Opened 2020-10-27 15:50 UTC by szaffarano

… associated code

2020-10-27 17:28 UTC, szaffarano commented
--validate

2020-10-28 12:17 UTC, elrodro83 requested changes
You didn't remove the logic associated with the system property

2020-10-28 18:27 UTC, elrodro83 requested changes

2020-10-28 18:27 UTC, elrodro83 commented on core/src/main/resources/META-INF/mule-module.properties
> -                              org.mule.runtime.core.api.context.thread.notification,\
keep all the classes/interfaces from this package as deprecated

2020-10-28 19:19 UTC, elrodro83 approved these changes

2020-10-28 22:16 UTC, merged