MULE-18984: Dynamic Configurations are not expired until the flow ends.
mulesoft/mule pull request #9737
Opened 2020-11-16 21:34 UTC by SebaElizalde

2020-11-19 18:19 UTC, marianogonzalez requested changes

2020-11-20 12:58 UTC, SebaElizalde commented on modules/extensions-spring-support/src/test/java/org/mule/test/module/extension/DynamicConfigExpirationTestCase.java
> +        return disposedStatuses.size() == 2;
What do you mean? Can you ellaborate?

2020-11-20 13:18 UTC, marianogonzalez commented on modules/extensions-spring-support/src/test/java/org/mule/test/module/extension/DynamicConfigExpirationTestCase.java
> +        return disposedStatuses.size() == 2;
the condition should be `>=` but asciidoc attacked

2020-11-20 13:30 UTC, marianogonzalez requested changes

2020-11-20 13:30 UTC, marianogonzalez commented on modules/extensions-spring-support/src/test/java/org/mule/test/module/extension/DynamicConfigExpirationTestCase.java
> +    disposedStatuses = new ArrayList<>();
null

2020-11-20 13:52 UTC, marianogonzalez approved these changes

2020-11-20 20:03 UTC, SebaElizalde commented
--validate

2020-11-21 00:55 UTC, merged