MULE-19073: Exception in Catch Exception Strategy does not roll back transaction
mulesoft/mule pull request #9876
Opened 2020-12-22 13:00 UTC by pabloperalta

2020-12-29 17:14 UTC, fsgonz requested changes

2020-12-29 17:14 UTC, fsgonz commented on core/src/main/java/org/mule/exception/TemplateMessagingExceptionStrategy.java
> +                throw new MessagingException(CoreMessages.createStaticMessage("There was an error processing the catch strategy"), event, e);
static import

2020-12-29 17:14 UTC, fsgonz commented on core/src/test/java/org/mule/exception/CatchMessagingExceptionStrategyTestCase.java
> +        when((Class<String>) mockMuleEvent.getMessage().getDataType().getType()).thenReturn(String.class);
Why is this needed?

2020-12-29 17:14 UTC, fsgonz commented on modules/cxf/src/test/resources/catch-exception-strategy-flow-conf-httpn.xml
> +                        return new String(message.getOriginalPayload())
Why is this needed?

2020-12-30 19:43 UTC, pabloperalta commented on modules/cxf/src/test/resources/catch-exception-strategy-flow-conf-httpn.xml
> +                        return new String(message.getOriginalPayload())
No longer needed

2020-12-30 19:44 UTC, pabloperalta commented on core/src/test/java/org/mule/exception/CatchMessagingExceptionStrategyTestCase.java
> +        when((Class<String>) mockMuleEvent.getMessage().getDataType().getType()).thenReturn(String.class);
No longer needed

2021-01-05 14:53 UTC, mbuchwald approved these changes

2021-01-05 16:21 UTC, merged