MULE-18873: Scatter-Gather routes are dropping events during Flow-Ref…
mulesoft/mule pull request #9962
Opened 2021-01-11 18:43 UTC by IvanAndresFritzler

… processing

(cherry picked from commit 79ce3b61d30e5d3a37c83faab8ac3f8cb99a0a33)

2021-01-11 19:05 UTC, eze210 requested changes

2021-01-11 19:05 UTC, eze210 commented on src/main/resources/META-INF/MANIFEST.MF
> +Manifest-Version: 1.0
Why is this manifest needed?

2021-01-11 21:40 UTC, IvanAndresFritzler commented on src/main/resources/META-INF/MANIFEST.MF
> +Manifest-Version: 1.0
Removing...

2021-01-12 13:58 UTC, eze210 approved these changes

2021-01-12 14:06 UTC, merged